### ISSUE TITLE
Create can.view.animation for animation attributes

### ISSUE THREAD

**Issue by jandjorgensen** [bitovi/canjs#1005]
[VOTE HERE](http://bithub.com/event/36984)

Documentation and Scaffolding: [canjs/view/animation/animation.js](https://github.com/bitovi/canjs/blob/can-view-animation/view/animation/animation.js)
Example Usage: [canjs/view/animation/doc/animation.md](https://github.com/bitovi/canjs/blob/can-view-animation/view/animation/doc/animation.md)

**Comment by daffl** [comment]
This should be in https://github.com/canjs/can-animate now right?
