### ISSUE TITLE
define::set doc issues

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1047]
http://canjs.com/docs/can.Map.prototype.define.set.html

- [x] - code highlighting isn't working
- [x] - code examples are too wide
- [x] - merge example might not work

**Comment by alexisabril** [comment]
`I think maybe the problem is that: .attr(PROP, Object) merges by default, but .attr(PROP, Map) sets.`

Both calls will set: http://jsbin.com/gozadi/edit?js,console
