### ISSUE TITLE
Feature: allow can.fixture to distinguish requests by query parameters

### ISSUE THREAD

**Issue by isadovskiy** [bitovi/canjs#1058]
It would be great to allow can.fixture() to return different fixtures for the URLs, which are different just in query params.

For example, some service can require calls something like http://some.service.com/action?method=XXX. So I'd like to map responses for different action methods to different fixtures easily.

Refer: https://forum.javascriptmvc.com/topic/can-fixture-and-requests-distinguishing-by-query-params#home

**Comment by daffl** [comment]
This functionality is supported in https://github.com/canjs/can-connect, so we can move the discussion there.
