### ISSUE TITLE
Lexical semantics for can.Component

### ISSUE THREAD

**Issue by zkat** [bitovi/canjs#1069]
`can.Component` should have lexical semantics for its light dom. Consider this fiddle: http://jsfiddle.net/5D4FK/2/

Lexical semantics would shield the user from internal implementation details of the component. Likewise, they would shield the Component itself from unintended (or even intended) injection from the outside. Conceptually, the user should never know/care about the internal details of a component's shadow dom and interact with it purely through its exposed API (attributes and the light DOM, rendered in the lexical template context).

**Comment by daffl** [comment]
Closed via #1429
