### ISSUE TITLE
Missing documentation in can.Component

### ISSUE THREAD

**Issue by imjoshdean** [bitovi/canjs#1070]
Functions/events such as:

- init
- inserted
- Possibly more

If they are vital to how can.Component works, they should be in can.Component.

**Comment by alexisabril** [comment]
Closed by https://github.com/bitovi/canjs/commit/c5b30740a24c7d47da2c314987aa91e64734754b

Note: We don't actually document `init` in most places, although it's available on everything that inherits from can.Construct.
