### ISSUE TITLE
define getter isn't passed the current value as expected

### ISSUE THREAD

**Issue by Bajix** [bitovi/canjs#1080]
If you use define with value to initialize a can.Map property, the getter will be passed the current value. However, after setting the current value, the getter is not being passed the new value.

http://jsfiddle.net/wJV5j/

**Comment by justinbmeyer** [comment]
@Bajix taking a look at this again ... I'm going to make the original fiddle work.

**Comment by Bajix** [comment]
@justinbmeyer This was resolved in 2.2.0 but wasn't included within the milestone
