### ISSUE TITLE
registerSimpleHelper

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1102]
We should support a simple helper so people don't have to check if helper arguments are a compute.  For example, a nice link helper could be written like:

```js
can.stache.registerSimpleHelper("link", function(name,options){

  return can.stache.safeString( can.route.link(name,options.hash) );
});
```

`registerSimpleHelper` would simply register another helper, but would make sure all the arguments and options.hash that are computes are converted to their normal value.

**Comment by daffl** [comment]
This is included in 2.3.
