### ISSUE TITLE
can-href link helper

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1103]
[VOTE HERE](http://bithub.com/event/40391)

We should add a `link` stache/mustache helper or component or custom attribute.

### Helper

```
<li>{{link recipe.name page='recipe' id=recipe.id}}<li>
```

Pros - I like the syntax
Cons - Can't easily pass the "style" argument to can.route.link.

## Custom Attribute

```
<li><a can-href='{page="recipe" id=recipe.id}'>{{recipe.name}}</a></li>
```

Pros - can customize the style, happens directly on a link.
Cons - UGLY

## Custom element

```
<can-link page="recipe" id="{recipe.id}">{{recipe.name}}</a></li>
```

Pros - pretty, fits in with how components get hooked up
Cons - What about attributes that should be ignored?  Do we need a syntax of specifying that?  We'd have to add "style".  Maybe `data-X` prevents cross binding on that property?

Qs - would we put an `<a>` inside or would we implement click / keypress ourselves?

A - we would have to put the `<a>` inside if we want right click and open in new window ... indexing ... etc.

**Comment by justinbmeyer** [comment]
For consistency, I think we are going to go with this:

```
<li><a can-href='{page="recipe" id=recipe.id}'>{{recipe.name}}</a></li>
```

This will be easiest to implement and work similar to can-EVENT and passing options to helpers..

**Comment by justinbmeyer** [comment]
# can-href

Sets an element's href attribute so that it's url will set the specified attribute values on [can.route].

@siganture `can-href='{[attrName=attrValue...]}'`

@param {String} attrName
@param {can.stache.key} attrValue

## Use


With no pretty routing rules, the following:

```
<li><a can-href='{page="recipe" id=5}'>{{recipe.name}}</a></li>
```

produces:

```
<li><a href='#!page=5&id=5'>{{recipe.name}}</a></li>
```

If pretty route is defined like:

```
can.route(":page/:id")
```

The previous use of `can-href` will instead produce:

```
<li><a href='#!page/5'>{{recipe.name}}</a></li>
```

You can use values from stache's scope like:

```
<li><a can-href='{page="recipe" id=recipeId}'>{{recipe.name}}</a></li>
```

If `recipeId` was 6:

```
<li><a href='#!page/6'>{{recipe.name}}</a></li>
```

If `recipeId` is observable and changes to 7:

```
<li><a href='#!page/7'>{{recipe.name}}</a></li>
```

**Comment by stevenvachon** [comment]
Wouldn't `<a can-href="{page:'recipe', id:recipeId}">` be more javascript-like ?

**Comment by justinbmeyer** [comment]
@stevenvachon it wouldn't be more mustache/stache like.  Plus we already have a parser for `foo=bar`.

**Comment by stevenvachon** [comment]
Ah, yes: http://handlebarsjs.com/expressions.html#helpers
Thanks

**Comment by daffl** [comment]
This has been added in 2.3 (but is already deprecated in favour of the `routeCurrent` and `routeUrl` helpers).
