### ISSUE TITLE
Mustache helper has no rendered output, if the output is 0.

### ISSUE THREAD

**Issue by asavoy** [bitovi/canjs#1109]
When writing an inline Mustache helper, if the result from the helper is the number zero, then it won't be rendered.

See example: http://jsfiddle.net/qYdwR/1601/

Context: I'm trying to write a helper for conveniently handling numerical values, rounding them to the nearest whole number, and displaying null values in a consistent way.

**Comment by alexisabril** [comment]
This also exists in stache due to: https://github.com/bitovi/canjs/blob/minor/view/stache/expression.js#L329

Adding a test and leaving open while I verify if we should be checking for all falsey values, or just undefined.

**Comment by DesignByOnyx** [comment]
Hey @alexisabril - I have fixed Stache already (haven't pushed yet) and know where to fix this one. Do you want me to go ahead and do it?

**Comment by alexisabril** [comment]
@DesignByOnyx Yeah, merge in that test I wrote(or copy it) and we should be good.
