### ISSUE TITLE
Validation improvements

### ISSUE THREAD

**Issue by moschel** [bitovi/canjs#1111]
[VOTE HERE](http://bithub.com/event/40885)

It seems like can/map/validate is sort of like can/map/define::setter but has several differences, and it might make sense to merge them.

Setter supports async, validations doesn't.

Validations supports an "errors" object and "errors" events, both of which are very useful.

I propose merging the validations plugin into define.  Or at least making them work together rather than separately.

A couple thoughts:

* Although `validate` would be similar to `set`, I think `validate` should be separate, because I can think of cases where you'd want the hook provided by `set` and validation logic separate.
* The validate callback should be called with a success, error so you can do serverside validations
* errors should be observable (#355)

**Comment by daffl** [comment]
I think we can move this discussion into https://github.com/canjs/can-validate
