### ISSUE TITLE
can.fixture has no way to allow AJAX calls to circumvent it, if necessary

### ISSUE THREAD

**Issue by imjoshdean** [bitovi/canjs#1131]
I have a use case where all AJAX calls go through a single URL, very RPC-like. I created a fixture service to work with this, but I need to bypass fixture calls optionally. Simply need to pass something like "canfixture: false" to the AJAX settings and check for it on the fixture prefilter.

**Comment by daffl** [comment]
Closed via #1453. Will merge into master shortly.
