### ISSUE TITLE
Block level elements should be able to render inside anchor tags

### ISSUE THREAD

**Issue by jandjorgensen** [bitovi/canjs#1134]
Can not currently render a block-level element inside an `<a>` tag since it is an inline element. 

HTML5 spec allows putting block-level elements inside anchors.  HTML 4.01 *allows* block elements inside anchor tags, though it requires additional CSS to make sure it behaves properly--rendering this way prevents the CSS workaround.

Template:
```html
<a href="#">
<h1>Foo</h1>
</a>
```

Result:
```html
<a href="#"></a>
<h1>Foo</h1>
```

Example Here:
http://jsfiddle.net/dcgSY/6/

**Comment by daffl** [comment]
@ccummings Done. This is needed in several projects and a must if you want to use Bootstrap markup.
