### ISSUE TITLE
Strange live binding behavior with input elements

### ISSUE THREAD

**Issue by jawshooah** [bitovi/canjs#1142]
When using a template of the form
`<input type="text" <% if (obj.attr("val")) { %> value="<%=obj.attr("val")%>" <% } %>>`
or the equivalent in Stache:
`<input type="text" {{#obj.val}} value="{{obj.val}}" {{/obj.val}}>`
the placeholder `"__!!__"` is inserted in place of the new value when the input is changed for the first time. This occurs when using either [Stache](http://jsfiddle.net/qYdwR/1677/) or [EJS](http://jsfiddle.net/qYdwR/1675/).

Forum post [here](https://forum.javascriptmvc.com/topic/strange-live-binding-behavior-with-input-elements).

**Comment by justinbmeyer** [comment]
Closing b/c we aren't going to try to fix this as this is fixed in stache.  Here's the test I wrote:

```
test("live binding attributes with input value (#1142)", function(){
	
	var map = new can.Map({
		counter: {test: 0}
	});
	var template = can.stache('<input type="text" {{#counter.test}}value="{{counter.test}}"{{/counter.test}}>');
	var input = template(map).firstChild;
	
	equal(input.value, "", "no value");
	
	map.attr("counter").attr("test",1);
	
	equal(input.value, "1", "no value");
});
```

**Comment by jawshooah** [comment]
Not ecstatic about that, as we have a pretty extensive set of EJS templates that would take a lot of work to migrate to Stache. But I recognize that it's not a trivial bug to fix.
