### ISSUE TITLE
CanJS Inspector

### ISSUE THREAD

**Issue by retro** [bitovi/canjs#1144]
[VOTE HERE](http://bithub.com/event/41401)
I'd like to make something like [Ember Inspector](https://github.com/emberjs/ember-inspector) but for CanJS

I was thinking about the following features:

- Inspecting the component scope
- Inspecting the controls bound to an element
- Inspecting the current model requests
- Inspecting the app state object (whatever is bound to can.route map)

Can you think of any other features we could need?

**Comment by alexisabril** [comment]
Closing as we now have an alpha inspector with its own repository: https://github.com/canjs/can-devtools
