### ISSUE TITLE
can.Model.parseModels passed different arguments than documented

### ISSUE THREAD

**Issue by Alfredo-Delgado** [bitovi/canjs#1194]
[can.Model.parseModels.html](http://canjs.com/docs/can.Model.parseModels.html) states ``` can.Model.parseModels(data, xhr) ```, but as [this fiddle](http://jsfiddle.net/gb43k/2/) shows, there's a third argument between data and xhr.

**Comment by alexisabril** [comment]
This was modified in CanJS 2.2.x to match the currently documented API. data & xhr are the only two arguments passed. Noting for review.
