### ISSUE TITLE
can.connect for advanced persistent data behavior

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1213]
[VOTE HERE](http://bithub.com/event/43923)

## Goal

Create a plugin that allows mixin behavior for CRUD lifecycle events. For example, creating a `Person` can.Map and adding RESTful behavior might look like:

```js
Person = can.Map.extend({ ... });

can.connect.resource("/people", Person) 

Person.findAll({}) //-> deferred
```

- Creating and using the mixins should be easy.
- can.Model should use this and be backwards compatible.

### Model instance store

Provides the same behavior as the current model-store

#### Use

```js
can.connect.store(Person,{id: "personId"})
```

#### Implementation

Hooks into:

 - findOne / findAll lifecycle
 - bind / unbind

#### Use

```js
can.connect.live(Person,{
  // how to connect to event stream
  // called when items have been requested
  // able to tell system when an item is created / updated
  // destroyed
  connect: function(){},
  // called to disconnect
  disconnect: function(){}
})
```

#### Use

```js
can.connect.localCache("people", Person)
```

### Live lists

Live lists would automatically put created items in the list when the realtime connection pushed a new item.

#### Use

```js
can.connect.live(Person,{});
can.connect.liveLists(Person, {
  // compares the params a list was retrieved with 
  // and an instance and indicates if the instance
  // belongs in the list
  compare: function(){}
})
```

### Queue Plugin

Allows immediate saving and queuing of requests.

### Use

```js
can.connect.queue(Person)
```

### Implementation

Hooks into:

- create / update / destroy lifecycle
- backup / restore?

**Comment by whitecolor** [comment]
Is there any progress for this issue? BTW wy can.Model doesn't have default method like ```sync``` that would request server new data for partucular instance and merge it with existing data on the client?

**Comment by justinbmeyer** [comment]
findOne can do this

**Comment by whitecolor** [comment]
I use this method, but I'm not sure that it will work correctly if model instance is not in store.

```findOne``` only will merge incomming data with model with the same id that is in store.

**Comment by daffl** [comment]
This is available in https://github.com/canjs/can-connect
