### ISSUE TITLE
Problem with can.stache and IE 11

### ISSUE THREAD

**Issue by daffl** [bitovi/canjs#1220]
Reported by @danwoods on IRC, it seems like there is a missing dependency (or default) for can.stache in 2.1.3 on IE 11: https://gist.github.com/danwoods/8be3e25e16399589a712

**Comment by pYr0x** [comment]
this bug is still present in all  2.1.*... can you pull danwoods fix into the 2.1.*  branch?

**Comment by daffl** [comment]
There is no 2.1 branch. Are you having issues upgrading to 2.2?

**Comment by pYr0x** [comment]
i have an old project that is still in progress. there is no testing units for the site, so i cant update to a new major release until testing each part of the website. do canjs follow the Semantic Versioning Specification at all?

**Comment by matthewp** [comment]
Yes, can follows semver. 2.2 is a minor release so it is api compatible.
