### ISSUE TITLE
can.compute nested key behaviour inconsistency with map bindings

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/canjs#1231]
`can.compute`s with `attr("value.nested")` do not behave the same as `attr("value").attr("nested")` in a map binding.

http://jsfiddle.net/prometh/La806u2d/

**Comment by chasenlehara** [comment]
+1, we ran into [an issue caused by this bug in Sam’s](https://github.com/bitovi/samsclub/issues/4218).

**Comment by justinbmeyer** [comment]
Closed by #1696.
