### ISSUE TITLE
can.Compute as a prototype based can.compute

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1255]
Creating an issue to track the following feature:

Refactor can.compute to instead have existing methods on a prototype, as opposed to creating closure scoped methods upon each compute.

For example:

    var c = can.compute(1)

would change to

    var c = new can.Compute(1)

can.compute API will still be supported, however can.compute internals will be mapped to can.Compute.

**Comment by daffl** [comment]
Also merged and included in 2.3.

**Comment by pYr0x** [comment]
sorry... cant find this feature in repo

**Comment by daffl** [comment]
In minor (and the 2.3 I'm just wrapping up) you can find it here: https://github.com/bitovi/canjs/blob/master/compute/proto_compute.js and as `can.Compute`.

**Comment by justinbmeyer** [comment]
@pYr0x it's not documented.  I'm not sure if it will be.  Currently it's for internal use only.  It's a bit faster then `can.compute`, but not enough to make it worth it for everyone to use.
