### ISSUE TITLE
amd build doesn't remove steal-only code

### ISSUE THREAD

**Issue by gsmeets** [bitovi/canjs#1273]
When I check out the main repo and run `grunt build` on my local machine the build doesn't remove the steal-only code. I suppose it is meant to do this? The code I download from the site doesn't have this code still in there.

An example is line 715-734 from can/view.js:

````
//!steal-remove-start
	if (window.steal) {
...
````

I need to do my own build unfortunately to fix the canjs paths, as a path directive in my require.config completely kills any way to use loader plugins. Am I missing some grunt option to remove the code between those steal comments?

**Comment by daffl** [comment]
I just verified that with the new build system in 2.2 (which is now in master) dev code does get removed properly. 2.2 is about to land within the next two weeks.
