### ISSUE TITLE
rename can.Component scope to context?

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/canjs#1300]
It was suggested way back in #635 and I agree with it.

`scope` may be good for those migrating from AngularJS but to everyone else, I think that `context` makes more sense. It also causes less confusion with can-EVENT function arguments:
```js
context: {
    canEventFunction: function(scope, element, event) {
        // scope vs context
    }
}
```

Maybe a 3.0 feature?

**Comment by justinbmeyer** [comment]
Some definitions:

## In Mustache

- context - the initial object a template will look within for key values
- key - an identifier
- scope - a `can.view.Scope` that represents a context and a parent context.
- scope chain - all contexts a key might be found within for a certain area of a template

## In attribute helpers

- `can-scope` - a helper that binds a component's "scope" to a particular key value in the current context.

## In can.Component

- scope - A definition of a `can.Map` that is used to render the component's template.  This is normally used as a view model.

**Comment by daffl** [comment]
Will be renamed to `viewModel` via #1512.
