### ISSUE TITLE
test pages should point to local qunit resources as opposed to the remote cdns

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1351]
Currently we point qunit.js and .css to their cdn locations. This is done for the purpose of running tests via TravisCI. We should revert to having these resources locally to allow for running tests offline.

**Comment by daffl** [comment]
This has been fixed. Test pages now look like https://github.com/bitovi/canjs/blob/master/component/test.html using [steal-qunit](https://github.com/bitovi/steal-qunit). We just have to make sure that we add those to the GitHub pages otherwise the tests won't run.
