### ISSUE TITLE
can.view.attr won't trigger in can.mustache if no value is provided

### ISSUE THREAD

**Issue by savinger** [bitovi/canjs#1353]
can.view.attr('foo-bar', function(el, data) {
      $(el).html('Hello World!');
    });
    $('body').append(can.mustache('<div foo-bar></div>')());
    $('body').append(can.stache('<div foo-bar></div>')());

http://jsfiddle.net/fjaq8h66/

**Comment by justinbmeyer** [comment]
Does this happen in stache?

**Comment by savinger** [comment]
Nope. Maybe this fiddle is more clear: http://jsfiddle.net/fjaq8h66/1/

**Comment by ccummings** [comment]
+1
This doesn't happen in stache.
the scanner does not ouput a call to can.view.pending unless the attribute has an `=`

**Comment by daffl** [comment]
This seems to be fixed in minor.
