### ISSUE TITLE
Proposal: `can-scope` for exporting scope into the surrounding context.

### ISSUE THREAD

**Issue by zkat** [bitovi/canjs#1362]
## Proposal

As we start using components more, we will want to add methods to our components that are meant for external use. #881 was an attempt to address this issue, but in keeping with our policy of isolating the DOM and ViewModel layers, I think it's better to expect these methods to mainly be accessed through the component viewmodels.

To facilitate this, I think following something similar to what Polymer does, by providing a simple mechanism for giving easy accessible names to child scopes. These names would be accessible directly through the component templates, and further 

I propose using a `can-scope` attribute for facilitating access to child component functionality in a template, and in the component's viewModel. I further propose that non-`Component` html tags that use the `can-id` attribute will automatically be treated as a `can-value`, and have that value be accessible instead.

Concretely, `can-scope` will export the tag's scope into a name in the surrounding template. The attribute will **also** automatically add `can-value`-like functionality if used on a non-component.

## Justification and Notes

This may require #1069 for proper operation, and will be much improved by #1360. Having #1361 would also be much more valuable here, since we would be able to just directly pass arguments to child scope methods.

## Examples

```html
<gt-placement-request param-new-name="{nameInput.value}" can-scope="{allPlacementsReq}" can-request-done="{notifyDone allPlacementsReq.value}">
</gt-placement-request>
<bs-button can-click="{allPlacementsReq.go placement}">Submit</bs-button>
<input can-scope="{nameInput}">
{{#if allPlacementsReq.error}}
    There's an error! {{allPlacementsReq.error}}
{{/if}}
```

```js
 // in JS, too
scope: {
  getPlacements: function() {
    return this.attr("allPlacementsReq").go();
  }
}
```

**Comment by justinbmeyer** [comment]
Some thoughts on this (that I've already discussed with Kat):

 - I personally like `can-id` more than `can-scope`, even if this is not as accurate as `can-scope` largely because it is likely to be the overwhelming use case and people are so darn familiar with adding an ID.
 - I think that we can still have a side table with component names so they can be referenced directly within the same scope.  This changes the current example to:

```
<gt-placement-request param-new-name="{nameInput.value}" can-request-done="{notifyDone gt-placement-request.value}">
</gt-placement-request>
<bs-button can-click="{gt-placement-request.go placement}">Submit</bs-button>
<input can-scope="{nameInput}">
{{#if allPlacementsReq.error}}
    There's an error! {{allPlacementsReq.error}}
{{/if}}
```

**Comment by zkat** [comment]
I still don't like the idea of keeping a table of components. It has relatively little value above just doing `can-scope` and is much less flexible as soon as you start putting more than one component for any reason: You're going to randomly kill existing code without necessarily realizing you just did.

That said, the original intend of `can-scope` was to copy something that Polymer does with element `id`s: It scopes them to the shadow DOM, and puts any element with an ID into the `$` object using that ID as a name. An alternative implementation to this feature, thus, is to just commit to how the shadow dom is expected to work and add a `can.view.attr` trigger on the `id` attribute that uses the id to add to the current component scope, but only works inside can.Component templates, or something.

I don't like `can-id` because I think it's worth driving the point home that you're not getting access to the DOM element here (as you do in Polymer), but the scope-slash-viewmodel. You're also not exactly giving it a name, but actually hooking it up to some two-way binding, just like any other two-way bind on attributes.

**Comment by justinbmeyer** [comment]
Regarding this, would

```
<gt-placement-request param-new-name="{nameInput.value}" this="{allPlacementsReq}" can-request-done="{notifyDone allPlacementsReq.value}">
</gt-placement-request>
<bs-button can-click="{allPlacementsReq.go placement}">Submit</bs-button>
<input this="{nameInput}">
{{#if allPlacementsReq.error}}
    There's an error! {{allPlacementsReq.error}}
{{/if}}
```
Be enough?  This would one-way export `this` into the parent scope.

**Comment by justinbmeyer** [comment]
cc @daffl where did you get on this for 2.3?

**Comment by justinbmeyer** [comment]
@daffl checked what you did:

```
can.view.attr(/\[[\w\.]+\]/, function(el, options) {
		var prop = removeBrackets(el.getAttribute(options.attributeName));
		var name = removeBrackets(options.attributeName, '[', ']');

		can.one.call(el, 'inserted', function() {
			var value = can.viewModel(el);

			if(prop !== 'this' && prop !== '.') {
				value = value.attr(prop);
			}

			options.scope.attr(name, value);
		});
	});
```

this won't change if the value.attr(prop) changes.  In that case, we should listen to changes in it and update the `scope.attr`.

**Comment by daffl** [comment]
This can be done in 2.3.0 with the new view bindings (http://canjs.com/2.3-pre/docs/can.view.bindings.html)
