### ISSUE TITLE
Problems with attributes named like "standard"  value, checked, etc

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1368]
I want to use attributes for component name like:

1) ```checked```
2) ```value```

but it seems I have an issue this this, so I have to use name like ```is-checked```

```javascript
can.Component({
    tag: 'my-comp',
    template: 'value: {{value}}<br>checked:{{checked}}<br>isChecked: {{isChecked}}',
    
    scope: {
        value: '@',
        checked: '@',
        isChecked: '@'
    }
    

})

var map = new can.Map({done: 'true'})

$('body').append(can.mustache('<my-comp value="{{done}}" checked="{{done}}" is-checked="{{done}}"></my-comp>')(map))
```

Fiddle: http://jsfiddle.net/xKc3H/566/

the output:
```
value: __!!__
checked:__!!__
isChecked: true
```

The same problem in stache.

**Comment by justinbmeyer** [comment]
@daffl `value="__!!__"` is only for mustache right?  We aren't going to fix these types of issues in mustache, only stache.

@whitecolor You have to use `{}` to pass a value other than a string.  

But, you can use `{{}}` to pass string values.  However, in this case, you really want to be passing a boolean.

So with #1371 by @zkat the following should work in 2.2:


```html
<my-component {{#selected}}checked{{/selected}}> ....
```

```
can.Component.extend({
  tag: "my-component",
  scope: {
    define: {checked: {type: "htmlbool"}}
  }
})
```

Closing and marking this as 'wontfix' for now.  If I'm wrong, please comment and I will reopen.
