### ISSUE TITLE
can/map/define default behaviors with "*"

### ISSUE THREAD

**Issue by imjoshdean** [bitovi/canjs#1373]
It would be really nice if we could create default behaviors for map attributes. For example, I have an AppState object tied to my can.route; however, not every attribute I want to throw on the AppState should be serialized and put into the route. Right now I have to define every attribute I want to put in my AppState with:

```js 
attributeName: {
    serialize: false
}
```
What would be nicer to have would be to have a catch all definition for attribute behaviors, say, `"*"`, that would provide a set of behaviors for all attributes unless otherwise defined. So for example:

```js
serializeOne: {
    serialize: true
},
serializeTwo: {
    serialize: true
},
"*": {
    serialize: false,
    type: "string"
}
```

`serializeOne` and `serializeTwo` would be typed as strings and be serializable; all other attributes on the Map wouldn't be serialized but will be also typed as strings.

**Comment by justinbmeyer** [comment]
@daffl @imjoshdean what would it take to get this in for can.List as well?

**Comment by whitecolor** [comment]
Is ```*``` going to afffect ALL the attributes or only that are in ```define``` object?

**Comment by imjoshdean** [comment]
@whitecolor It will affect all attributes - but it will have the same minimal footprint that define has already.

**Comment by whitecolor** [comment]
Does this work? In master?

**Comment by daffl** [comment]
Yes. But @imjoshdean still needs to add documentation (#1449)

**Comment by whitecolor** [comment]
http://jsfiddle.net/xKc3H/367/

```javascript
var Model = can.Model.extend({

    define: {
        name: {
            value: 'Alex'            
        },
        '*': {
            serialize: false
        }
    }
})


var model = new Model({age: 10, name: 'John'})

console.log(model.serialize())
```

Why result is `Object {name: "John"}` ? I thought no props should be serialized, no?

**Comment by imjoshdean** [comment]
@whitecolor Your use case is the entire reason why I wrote the define default behavior to begin with. I'll have a fix in before end of weekend.

**Comment by imjoshdean** [comment]
@whitecolor - Check the provided diff. I added your test with a minor tweak to the define tests. Thanks for catching this, because as I said...your use case was the whole purpose to me making this feature. I want to tie AppState to can.route, but I don't want EVERYTHING put in AppState to be serialized.

**Comment by imjoshdean** [comment]
...aside from the linting erros. :S
