### ISSUE TITLE
Unable to use can.Map in place of can.Component helper

### ISSUE THREAD

**Issue by wishabhilash** [bitovi/canjs#1374]
I want to define a bunch of default helpers into a can.Map so that i can include them into my components without the need to rewrite them again in different components. I would just like to include the map into the component like this.

    can.Component.extend({
        ...
        helpers: new can.Map({...})
    })

This would be a great feature and if already available, please guide me. Thankx.

**Comment by justinbmeyer** [comment]
@wishabhilash Imo, it doesn't make sense to use a Map.  After all, we only have can.Map to provide observability.  Your helpers "objects" don't need to be observable.  

I'm going to close this b/c I don't understand the use case.  If you fell like this is a mistake, please try to explain more.
