### ISSUE TITLE
Firefox TypeError: missing argument 1 when calling function this[attr]

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1377]
In firefox I've got an error:
```error
TypeError: missing argument 1 when calling function this[attr]
```
on this line:
https://github.com/bitovi/canjs/blob/minor/map/map.js#L447

it breaks the app. In other browsers there is no such error.

Any thougths where the problem can be?

**Comment by whitecolor** [comment]
> Oh, so you had a can.Map that had an attribute called watch?
Yes.

**Comment by justinbmeyer** [comment]
Ah, this was reported here too: #632. 

Seems like we need a warning/docs to avoid the property name "watch".

**Comment by justinbmeyer** [comment]
Closing for #1437.
