### ISSUE TITLE
Map.Define docs not clear on Merging

### ISSUE THREAD

**Issue by marshallswain** [bitovi/canjs#1384]
The Merging sections needs clarification on this page: https://github.com/bitovi/canjs/blob/master/map/define/doc/set.md

Specifically this section:

>Merging

>By default, if a value returned from a setter is an object, array, can.Map, or can.List, the effect will be to replace the property with the new object completely. This is not the same as calling setting a property with plain old attr and passing an object into a property that was already a can.Map, which will merge the new properties with the existing map.

**Comment by moschel** [comment]
`contact.attr('info')` returns a can.Map

**Comment by marshallswain** [comment]
Thanks, @moschel.  That's nice and straightforward.
