### ISSUE TITLE
@@!!@@ inserted into template when compute used in template iterator

### ISSUE THREAD

**Issue by JustinLove** [bitovi/canjs#1385]
http://jsbin.com/jihale/1/edit?html,js,console,output

The full size version of this is using a function to calculate the option tags; when the function references any computes, the error occurs.  The same effect occurs if a helper is used to calculate the options.

**Comment by moschel** [comment]
If you change your init method to the following, it works as expected:

````js
    var template = $('#template').html()
    var fragment = can.mustache(template)(options, {})
    element.html(fragment)
    console.log(element[0].innerHTML)
````

Render will return a string representation of the template, but above returns a DOM fragment and renders it. Mustache is adding a placeholder for values that need to be live-bound to, which is replaced later by actual contents. I think calling .render will give the intermediate contents, not the replaced values.

I'm not sure if that's actually expected or not. @daffl will have to weigh in on that part. But in your code sample, its more correct to do what is done above, not to call .render and insert a string into the element.

**Comment by moschel** [comment]
To be clear, I don't think this is a bug. It might be a case of needing better documentation around .render. @JustinLove maybe the render docs don't specify that this isn't the intended use?

**Comment by JustinLove** [comment]
Huh.  I added render while debugging other stuff and didn't expect the behavior to be different.  At this point I've done too much with the component based system, but if it gets too painful I'll try switching to controls again.
