### ISSUE TITLE
can.import

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1386]
Upcoming features of CanJS will need integration for importing modules.  Examples are `can-app`, and `can.stache` having the ability to import components it depends on.

I'm proposing a `can.import` which will work very similar to `System.import`.  It will take a moduleName and return a promise that is resolved with the moduleName:

```
can.import("can-slider").then(function(CanSlider){
  
})
```

The default behavior of `can.import` will be to use the `System` loader, if that doesn't exist, it will use AMD, and then CJS.

Other module loaders (such as StealJS) might overwrite `can.import` to make sure the config has finished loading.

**Comment by whitecolor** [comment]
Is it possible to make it load multiple modules ```can.import("can-slider", "some-other")``` ?

**Comment by matthewp** [comment]
What will be the use-case for this?

**Comment by whitecolor** [comment]
Well what is the use case for this:

```
can.import("can-slider").then(function(CanSlider){

})
```
can you give the code example?
