### ISSUE TITLE
can.mustache templates don't resolve partial names against the scope.

### ISSUE THREAD

**Issue by john-charles** [bitovi/canjs#1388]
According to: http://canjs.com/docs/can.mustache.helpers.partial.html#section_PassingPartialsinOptions

When including a partial the name passed in is to be resolved first against the vm and then treated as a raw value if not found in the vm. This behavior does not happen, **instead the view always tries to load the raw partial value. This causes an empty template exception to be thrown.**

This bug applies to can.mustache templates.

Please see the following proof.
http://jsfiddle.net/johncharles/bxh7LaLs/3/

**Comment by justinbmeyer** [comment]
Closing and moving into #1389.

**Comment by cklanac** [comment]
Fixes #1388 and #1389 Passing partial set in options
