### ISSUE TITLE
can.stache and can.mustache templates don't resolve partial names against the scope.

### ISSUE THREAD

**Issue by john-charles** [bitovi/canjs#1389]
This issue relates to and may have common cause with https://github.com/bitovi/canjs/issues/1388

According to: http://canjs.com/docs/can.mustache.helpers.partial.html#section_PassingPartialsinOptions

When including a partial the name passed in is to be resolved first against the vm and then treated as a raw value if not found in the vm. This behavior does not happen, **instead nothing happens, no attempt to load the template appears to be made, no exceptions are thrown.**

This bug applies to can.stache templates.

Please see the following proof.
http://jsfiddle.net/johncharles/oayj40t9/2/

**Comment by justinbmeyer** [comment]
@john-charles 

> When including a partial the name passed in is to be resolved first against the vm and then treated as a raw value if not found in the vm. 

What do you mean by "VM"?  Do you mean view model?  In stache / mustache terminology, I think you mean the can.view.Scope.

Ok, this is a bug.  We will fix.
