### ISSUE TITLE
can-autorender

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1390]
Based on: https://github.com/bitovi-components/component-utils/blob/master/autoloader.js, I'm proposing a `can-autorender` attribute that will be used to automatically render templates.  For example:

```html
<body>
  <script type='text/stache' can-autorender id='demo'>
    <h1>{{message}}</h1>
  </script>
  <script src='canjs.js'></script>
  <script>
    $("#demo").scope().attr("message", "Hello World");
  </script>
</body>
```

Would result in:

```html
<body>
  <script type='text/stache' can-autorender id='demo'>
    <h1>{{message}}</h1>
  </script>
  <h1>Hello World</h1>
  <script src='canjs.js'></script>
  <script>
    $("#demo").scope().attr("message", "Hello World");
  </script>
</body>
```

This should be available on normal elements.  Consider:

```html
<body can-autorender type='text/stache'>
  <h1>{{message}}</h1>
  <script src='can.js'></script>
  <script>
    $("body").scope().attr("message", "Hello World");
  </script>
</body>
```

If `can-autorender` is on a non-script element, any scripts within that element should NOT be rendered as part of the template.

## Rendering

The embedded templates should be rendered on dom content loaded.

If the source element is in the `<head>` the rendered result will be appended to the `<body>`.

## Scope

If `can-autoload` is placed on a script tag, a `can.Map` instance will be available on the script element:

```js
$("script#demo").scope() //-> can.Map
```

It's possible that the scope will want to be accessed prior to rendering.  For this reason, can.scope should be made to create a can.Map instance if one does not already exist.  

## Other Considerations

- We might need to patch DOMContentLoaded for other libraries.
- We might want to specify a src so these templates can be loaded outside the page.

cc @sykopomp

**Comment by justinbmeyer** [comment]
I like `can-render` a bit more than autoload.  However, the plugin might be `can/view/render` which would conflict with the `can.view.render` function.  

We could put it under bindings as `can/view/bindings/render`.

**Comment by justinbmeyer** [comment]
Here's what the slider might look like with autoload:

```html
<script type='text/stache' can-autoload>
    <can-import from="can-slider"/>
	<can-slider></can-slider>
</script>
<script src="./node_modules/steal/steal.js" main="can/view/autoload"></script>
```

with render:

```html
<script type='text/stache' can-render>
    <can-import from="can-slider"/>
	<can-slider></can-slider>
</script>
<script src="./node_modules/steal/steal.js" main="can/view/render"></script>
```

I think `can.view.render` shouldn't be a concern b/c no one uses it and it doesn't even work for stache.

**Comment by justinbmeyer** [comment]
Other options:

- `can-bootstrap` - might conflict with a can-bootstrap project.

**Comment by sykopomp** [comment]
woo! +1!

`can-autoload` gets my vote over `can-render`.

Do you want me to just grab autoload.js as-is and make a pull request of it? As far as the `src=` feature goes, I think that should be a separate issue+PR. I'm assuming what you meant by that is that you want to be able to do:

```html
<script src=my/template/thing.stache type=text/stache></script>
```
Would be nice if we could omit the `type` in cases like this, but the browser won't cooperate with us on this one. :)

Finally: I'm not sure what patching is needed about the `DOMContentLoaded` thing. I'm not familiar with Moo and YUI. I assume Zepto has the same fudged `load` event jQuery does.
