### ISSUE TITLE
A splice where can.List ends up exactly the same should not produce any events.

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1399]
Contrary to #1277, a splice that ends up looking the exact same should not produce add and remove events.  This will make can.List work very similar to can.Map.  If you set an attribute to its existing value, no events are fired.

#1277 was confused because "add" events were fired without "remove" events.  Instead, no events should have been fired.

**Comment by daffl** [comment]
Closed via #1400
