### ISSUE TITLE
Class attribute has __!!__ when binding with component scope variable

### ISSUE THREAD

**Issue by asavoy** [bitovi/canjs#1403]
See this JSbin:
http://jsbin.com/memuzarida/1/edit?html,js,output

When trying to (conditionally) set a class attribute using a value in the scope, it ends up as `__!!__` instead.

Seems to depend on all these conditions:

* Applying to the `class` HTML attribute, and
* The value to apply comes from the component's scope, and
* must be conditional, e.g. wrapped in `{{#if}}` or `{{#someValue}}`
* must be a Mustache template

**Comment by asavoy** [comment]
Might be similar to #1151 and #1142 .

**Comment by justinbmeyer** [comment]
Thanks for reporting, but I think this is unlikely to be fixed.  2.2 is coming out soon and can.Mustache is deprecated.

**Comment by asavoy** [comment]
@justinbmeyer I thought CanJS uses SemVer? Or in 2.2 will it always use Stache, even for Mustache templates?

**Comment by justinbmeyer** [comment]
It is SemVer.  Unfortunately, Mustache will still be default (and deprecated).  But we still don't want people using it.  3.0 will probably be out next just so we can do away with Mustache as a default.

**Comment by justinbmeyer** [comment]
(I'll accept a fix if you submit one .. I'm just closing b/c I would rather spend time on improving other things and stache is a very strong replacement).
