### ISSUE TITLE
can.List.prototype.sortIndexes is defined but not referenced

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1404]
`sortIndexes` is defined here: 

https://github.com/bitovi/canjs/blob/8425837c343efd6828bba1040bdabdd26ab96bea/map/sort/sort.js#L31

But a search yields only one result: 

```bash
totes:canjs akagomez$ grep -rn "sortIndexes" .
./map/sort/sort.js:31:		sortIndexes: [],
```

It's possible that it's referenced using some funky string concatenation, but that seems unlikely to me since `sort.js` itself doesn't utilize it.

**Comment by justinbmeyer** [comment]
Is this an issue to remove that definition?  If so, and removing it causes no tests to fail, please remove it.  Thanks!
