### ISSUE TITLE
Can a parent component listens to child 'inserted' event?

### ISSUE THREAD

**Issue by Rendez** [bitovi/canjs#1405]
I've taken the &lt;tabs&gt;&lt;panel&gt;[...] example from the site to re-construct the components.

If we add an event to the tab component such as:
```coffeescript
# tabs_component
events:
  'panel inserted': ->
    console.log('here we are');
```
Why are only directly bound events being fired, but not when done via delegation?

**Comment by justinbmeyer** [comment]
Because the inserted event does not bubble.  It would kill performance.

However, are you only supporting modern browsers with mutation observers?  I can show you how to create a small plugin that will let you do something very similar to this.

**Comment by justinbmeyer** [comment]
Closing because we can't add this to CanJS until we drop support for IE<10.

**Comment by Rendez** [comment]
@justinbmeyer it would be great to see that plugin. I find it easier to insert components within this event, as in components that act as layout builders as well, based on data. I can better test my components when the views are split into separate files.
