### ISSUE TITLE
{{#is}} and {{#eq}} helper

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1406]
Are you considering adding stache/mustach ```{{#is}}``` helper in the core?

To allow view statement like this

```{{#is someAttr anotherAttr}} {{/is}}```

```{{^is someAttr 'someConstantValue' }} {{/is}}```

Having this is reducing the need of some exessive code to handle the view state, currenty it is done mainlty with {{if#}} helper,

{{#switch}} https://github.com/bitovi/canjs/issues/1264 migth be useful as well.

**Comment by justinbmeyer** [comment]
I'm not planning on adding it, but if you'd like to add it, I'll accept a pull request with tests+docs.

**Comment by whitecolor** [comment]
Should pull go to master or minor?

**Comment by justinbmeyer** [comment]
I would make it against master.

**Comment by whitecolor** [comment]
We use minor in for our projects currently. Anyway we found some strange bug that even don't work with {{#if}} helper, will pull it.

**Comment by justinbmeyer** [comment]
Awesome.  Thanks!
