### ISSUE TITLE
travis.yml before_script

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1418]
We'll need to modify https://github.com/bitovi/canjs/blob/minor/.travis.yml#L3 from:

`npm install jquery#1.11.0 && node_modules/.bin/bower install`

to

`node_modules/.bin/bower install`

and add jquery@1.11.0 to the package.json.

Currently to run CanJS tests locally on this branch you'll need to run `npm install`, then `npm install jquery...` prior to npm tests. `npm install jquery...` should not be necessary or hidden.

**Comment by justinbmeyer** [comment]
@alexisabril You shouldn't have to run `npm install jquery` for a peerDep. npm will install peerDeps.

**Comment by daffl** [comment]
This caused tons of issue with people forgetting to run it locally. I think we should be able to make it a peer and dev-dependency.

**Comment by daffl** [comment]
Nevermind, peerDependencies actually are being installed and @mjstahl is going to update this.
