### ISSUE TITLE
can.Model should support serialization override

### ISSUE THREAD

**Issue by marknadig** [bitovi/canjs#1450]
Currently, json responses from the server can be massaged in a model's parseModel override. However, there is no way to customize the serialization before the data is sent in a put/post. Our rest api has a bad habit of wanting to deal with nest responses; e.g.
{todo: {id: 1, name: "fix it"}}

Supporting a serializeModel() overridable method seems to close the loop in the API.

Discussed:
https://forum.javascriptmvc.com/topic/compliment-to-parsemodel-to-massage-data-before-sending#32525000001806001

**Comment by justinbmeyer** [comment]
Oh, I forgot.  can.Model does call `.serialize` and passes that to updated/ created.  Does that work for you?

**Comment by justinbmeyer** [comment]
Seems like you found `.serialize` too.  Closing b/c I think that should be "good enough" not to warrant an API addition.  Thanks!

**Comment by marknadig** [comment]
:+1: http://jsfiddle.net/digger69/t1b20j2b/4/
