### ISSUE TITLE
Make RequireJS work with can.import

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1456]

**Comment by matthewp** [comment]
Looks like there is already code: https://github.com/bitovi/canjs/pull/1396/files#diff-95ad04d772620344cfa50f85ba7adb64R96

I guess we just need a test to verify it is working?

**Comment by justinbmeyer** [comment]
It doesn't work.

**Comment by matthewp** [comment]
Interesting, is there an existing demo page or something to test with? Otherwise I'll create one.

**Comment by justinbmeyer** [comment]
There's a test page for steal's integration.

**Comment by matthewp** [comment]
One issue is that we are importing `can/view/stache/stache` which for amd it should just be `can/view/stache`. This is only true of amd so I think we can just denormalize it in this one place.

**Comment by matthewp** [comment]
I really don't like doing an amd check in autorender but can't think of a better way.

**Comment by justinbmeyer** [comment]
Yeah, this will be gone in 3.0

**Comment by daffl** [comment]
Closed via #1460
