### ISSUE TITLE
Make can.view.live utilize temporary stores

### ISSUE THREAD

**Issue by Bajix** [bitovi/canjs#1483]
Can.view.live is used within the {{#each}} helper to allow adding or removing members within an array to lazily create or destroy the respective DOM node. The current approach however doesn't optimize for list replacing, and will always do a full teardown. For a lot of operations, such as sorting, filtering, or replacing a list with a findAll promise, all result in lists with a subset of the same members.

I propose that during operations such as replace, we create a temporary store of DOM nodes to their respective values ( CID? ), and then recycle as much as possible before tearing down the remainder

**Comment by Bajix** [comment]
Sample use case:

```
notifications.replace(Notification.findAll());
```

Because of the way can.Model.stores work, the resulting array could likely in fact have a large intersect.

**Comment by Bajix** [comment]
After discussing this with Justin Meyer, the issues are:

For this to be advantageous, the time complexity of the solution would need to be O(N), or linear. Initially, this appeared as having a time complexity of O(N LOG(N))

A key value store neglects that Document Node's can only be attached once to a document fragment. Cloning would potentially be necessary

If @index is being read, then cloning may not be viable.

List replacing uses splicing, which is represented in two events: a remove event, followed by an add event. The current bindings aren't well suited for this. A batchNum like mechanism could be potentially used. This could potentially be represented by a new splice event.

This relates to the work for #1454 to create a move event, which could be represented as a splice event.

**Comment by web-mech** [comment]
:+1:

**Comment by justinbmeyer** [comment]
This is mostly closed by #1782.  It doesn't handle "move", however, simple mutations don't redraw the entire list.

If there are other cases our diff can be better at, please open an issue.
