### ISSUE TITLE
Section helpers for lists fully tear down whenever a member is added/removed

### ISSUE THREAD

**Issue by Bajix** [bitovi/canjs#1484]
When using lists within a section helper, if the list has a member added/removed, then the entire list is re-rendered.

To demonstrate:
http://jsfiddle.net/kaw0henc/

Like the {{#each}} helper, this should be optimized to reuse nodes as applicable

**Comment by justinbmeyer** [comment]
This is on purpose. #each should be used for incremental situations. #section should be used when the whole list is going to be replaced. In situations where the whole list is going to be replaced, #section is faster to display and update as there's less work to be done.
