### ISSUE TITLE
Better docs on iterating performance of #section and #each.

### ISSUE THREAD

**Issue by marshallswain** [bitovi/canjs#1488]
Based on #1484, I've seen this come up a few times.  The [sections](http://canjs.com/docs/can.stache.Sections.html) page and the [#each](http://canjs.com/docs/can.stache.helpers.each.html) page probably ought to have a section explaining differences in iteration.

**Comment by pYr0x** [comment]
i think @marshallswain  is right... this is big difference between those two helper that should be documented.
+1 for correct documentation

**Comment by alexisabril** [comment]
Referencing #1254 as that information should be included in this update.
