### ISSUE TITLE
Unbinding non bound property decrements binding counter

### ISSUE THREAD

**Issue by DVSoftware** [bitovi/canjs#1490]
This causes the premature object removal from the store as _bindings becomes 0 too early.
See the fiddle: http://jsfiddle.net/donejs/qYdwR/

**Comment by akagomez** [comment]
Is it possible that there was some sort of copy/paste error? because I can't see how that Fiddle relates to the issue you're logging.

**Comment by DVSoftware** [comment]
I forgot to fork the fiddle, so it was original template

http://jsfiddle.net/jnhaqL1e/

**Comment by akagomez** [comment]
I see. 

Looking into this a bit further, regardless of what effect calling `.off` has on the `this.__bindEvents[event]` array after calling `can.removeEvent`, the `this._bindings` count is decremented. 

```
		can.removeEvent.apply(this, arguments);  // Has no effect on `this.__bindEvents[event]`
		if (this._bindings === null) {
			this._bindings = 0;
		} else {
			this._bindings--; // Decrements despite not removing an event
		}
```
https://github.com/bitovi/canjs/blob/32f1f6633266918185ade66ac1c72029ffdbd456/util/bind/bind.js#L31-L36

Here's a failing test to accompany the issue: https://github.com/bitovi/canjs/commit/c9eddc3b268b89fa97edc96d7d3a21e023822d6b
