### ISSUE TITLE
getHelper for can.stache and can.mustache should not require options

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1497]
Currently, can.stache.getHelper requires the name of the helper as well as the options object: https://github.com/bitovi/canjs/blob/master/view/stache/mustache_helpers.js#L150

We should have a way to get a handle to a specific helper without passing options.

`can.stache.getHelper('each') //for example`

**Comment by justinbmeyer** [comment]
@alexisabril please add this this week or close the issue.  Thanks!
