### ISSUE TITLE
Use defineProperty for attributes getter setters

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1501]
Add some option to `map.define` plugin that will define property on the map object using `defineProperty` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

API variant:
```javascript
define:{
   fullName: {
      get: function(){..},
      property: true
      //defineProperty: true // as alternative
   }
}
```

**Comment by justinbmeyer** [comment]
Are you looking to support direct property access?

Instead of this, I've been thinking about a `can.define` that would let you to add behavior directly to prototypes like:

```js
MyConstructor = function(...){...}
can.define(MyConstructor.prototype,{
  first: "string",
  last: "string",
  fullName: {
    get: function(){ return this.first + " " + this.last }
  }
});
can.event(MyConstructor.prototype)

thing = new MyConstructor()
thing.first = "Alex"
thing.last = "Osh"

thing.fullName // "Alex Osh"

thing.bind("fullName", function(ev, newVal, oldVal){ ... })

thing.last = "Oshkosh"
```

**Comment by whitecolor** [comment]
`can.define` is fine, maybe `map/define` plugin could use it ternally to allow usage of its API.

**Comment by justinbmeyer** [comment]
@whitecolor '*' would not work.  With only getter / setters, we would need to know every property ahead of time for computes to work.  

Proxies would allow any property to work. Here's a prototype: https://github.com/canjs/can-observe.  Please join me in convincing Chrome to add them: https://twitter.com/mraleph/status/640144111627030528.

If you are interested in making something like this work, I can add you to the can-observe project.

**Comment by justinbmeyer** [comment]
Closing because this work should be done in can-observe.
