### ISSUE TITLE
autorender test failing

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1503]
In latest master the autorender test is failing in Chrome and Firefox. I'm investigating what the issue is.

**Comment by matthewp** [comment]
Pretty sure it's caused by this commit: https://github.com/bitovi/canjs/commit/18866d735149ed5c87e2227c346a258dfa72b64b

Before it would check if scope existed and if not create one, so that's why autorender is not working.  There's also another bug that was being masked before, [here](https://github.com/bitovi/canjs/blob/918d0dde322ee3577c72ac0fd8c64c239d002369/view/autorender/autorender.js#L44).  `el.attributes` is a `NamedNodeMap` whose children are `Attrs`, not strings. Will fix both.

**Comment by matthewp** [comment]
@daffl I think this definitely needs to be in 2.2.

**Comment by justinbmeyer** [comment]
Agreed. I must have forgotten to add it to the list of plugins so it gets built and tested.
