### ISSUE TITLE
Sort plugin fires a "reset" event for every item added with push/unshift

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1510]
My gut tells me this line should be moved outside the `while` loop: 

```javascript
can.batch.trigger(this, 'reset', [args]);
```
https://github.com/bitovi/canjs/blob/6fb12f5f56be10aa49567345452a35117fb8d5f2/map/sort/sort.js#L255

**Comment by daffl** [comment]
Closed via #1517
