### ISSUE TITLE
How to use xcharts in can.Component?

### ISSUE THREAD

**Issue by wishabhilash** [bitovi/canjs#1514]
I have tried initializing the 1st example (bar charts) from [this link](http://tenxer.github.io/xcharts/examples/) using a can.Component.

I tried it within the init function of the scope, however, the chart is not rendered. Is there any other approach am unaware of???

Kindly someone guide. Thanks.

**Comment by justinbmeyer** [comment]
use the inserted event

```
events: {
  "inserted": function(){
    // initialize xcharts here
  }
}
```
