### ISSUE TITLE
Using value and get in the same property throws errors

### ISSUE THREAD

**Issue by moschel** [bitovi/canjs#1521]
Breaking test showing this behavior here: https://github.com/bitovi/canjs/commit/b45012d612669f801c5211967669e1dc681abaa3

This test passes in https://github.com/bitovi/canjs/releases/tag/v2.2.0-pre.0 but fails in latest master branch.

**Comment by moschel** [comment]
Using git bisect was able to see that https://github.com/bitovi/canjs/commit/8826d1048d40021632494fffac16545d201487d6 is the commit where this problem was introduced

**Comment by moschel** [comment]
@alexisabril the new compute refactor stuff broke this. I could use your help or if @daffl or @justinbmeyer know this stuff, their help, figuring out why.

**Comment by moschel** [comment]
Here is the breaking test

````js
	test('value and get', function(){
		var MyMap = can.Map.extend({
		  define: {
		    list: {
		    	Value: can.List
		    },
		    hasList: {
		    	value: true,
		    	get: function(){
		          var list = this.attr('list');
		          var length = list.attr('length');
		          return length >= 1;
		    	}
		    }
		  }
		});

		var map = new MyMap();
		equal(map.attr('hasList'), false);
		
	});
````

After the breaking change, it seems to break because the getter for hasList is called when the map is created. 

Before the breaking change, hasList would initialize using its value, and not call the getter until hasList was read in the next line.

**Comment by moschel** [comment]
This is the line that causes the premature call to the getter: https://github.com/bitovi/canjs/blob/master/compute/proto_compute.js#L335. Why is that needed?

**Comment by justinbmeyer** [comment]
That line existed before: https://github.com/bitovi/canjs/blob/v2.1.4/compute/compute.js#L337.

I don't think that line is the problem.  Why is the getter called when the map is created?  I bet that wasn't happening before.

**Comment by moschel** [comment]
putting a return on the this._set function here: https://github.com/bitovi/canjs/blob/master/compute/proto_compute.js#L466 will fix this test, but breaks another test in can/compute. Should _set be returning the value of lastSetValue.set(newVal)?

**Comment by moschel** [comment]
Is it expected that a can.Compute.async's function (the asyncComputer) should be called whenever there is a call to .get or .set? The docs make it seem like it should only be called for .get, but this test: https://github.com/bitovi/canjs/blob/master/compute/compute_test.js#L660 make it seem like it should be called for either. That is the only test that breaks when the above change is applied.

**Comment by daffl** [comment]
As mentioned to @moschel, I am pretty sure that having a getter and a `value` is what is causing the issues. This causes the defaults to be set (in https://github.com/bitovi/canjs/blob/master/map/define/define.js#L30) and the getter to run during initialization.

I can't think of a use case where you would have a value and a getter at the same time.

**Comment by justinbmeyer** [comment]
You can have a getter with a single arg that would make perfect sense with a value property.
