### ISSUE TITLE
Rebinding to {scope.<...>} events broken in 2.2.0

### ISSUE THREAD

**Issue by ccummings** [bitovi/canjs#1529]
The RegEx [here](https://github.com/bitovi/canjs/blob/master/component/component.js#L383) prevents `{scope.<...>} <EVENT>` events from being rebound when `<...>` changes.

What usually happens is the Regex strips out the `scope.` or `viewModel.` leaving the key of whatever it is you are listening to. The RegEx properly turns `viewModel.whatever` into `whatever` but it turns `scope.whatever` into `.whatever`. this prevents the the rebinding when `whatever` changes so future changes to `whatever` are only handled by the `{viewModel.whatever <EVENT>` handler.

This JSBin shows the problem. Only the `{viewModel.item} change` message is logged.

**Comment by daffl** [comment]
This has been closed via #1528
