### ISSUE TITLE
attribute named "created" doesn't work on model 

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1530]
If model instance does have attribute named `created` (that come for example from server) this attribute does not work properly.

`instance.attr('created')` - actually gets the value, but it does not apper in view.
`instance.created` - is function (relates to 'created' event I believe)

Not sure if it shoud work by design. Ofcource there should be a list of reserved words by can, but I haven't seen such.

As workaround I currently "convert" it to `createdAt` on the client using `define` plugin.

**Comment by justinbmeyer** [comment]
Attr, change, created, updated, destroyed, init, setup. 

Any event triggered or method already on a model is off limits.

**Comment by daffl** [comment]
I thought that would just mean you can't access the property directly like `model.created`. I would expect it to show up in a view if it is available via `.attr`: http://jsfiddle.net/uc1m3L4j/2/
Is that just a precedence problem that (Mu)Stache is trying to run the function right away instead of looking it up via `.attr` first?

**Comment by whitecolor** [comment]
Yes it would be ok if it worked in views.

**Comment by justinbmeyer** [comment]
A "created" attr can't work in views.  The "created" model event would conflict with the "created" property change events.

**Comment by justinbmeyer** [comment]
> Is that just a precedence problem that (Mu)Stache is trying to run the function right away instead of looking it up via .attr first?

No, it's a different problem.

**Comment by justinbmeyer** [comment]
Closing because this doesn't really have a solution.  "created" is a reserved word in a `can.Model`.

**Comment by whitecolor** [comment]
I would you `create` and `update` events instead `created`, `updated`
