### ISSUE TITLE
{{#helper}} documentation examples are missing the "#"

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1535]
![screen shot 2015-03-19 at 3 43 24 pm](https://cloud.githubusercontent.com/assets/82166/6739451/0ae713c4-ce4f-11e4-85be-bac59ddc4d09.png)

**Comment by daffl** [comment]
This seems to be fixed now (see http://canjs.com/docs/can.stache.helpers.sectionHelper.html)

**Comment by akagomez** [comment]
Still wrong on the Mustache docs: http://canjs.com/docs/can.mustache.helpers.sectionHelper.html

**Comment by rasjani** [comment]
Also example in http://canjs.com/docs/can.mustache.tags.escaped.html under Looking up values in parent contexts doesn't have the closing '/' for chapters helper.
