### ISSUE TITLE
#unless helper is not working with an empty can.List

### ISSUE THREAD

**Issue by pYr0x** [bitovi/canjs#1538]
#unless is the counterpart of #each

as we know ( #1488 ), sections and #each work different.

#unless should work as the same as section inverse http://canjs.com/docs/can.stache.tags.inverse.html

here is the fiddle:
http://jsfiddle.net/jqeu9s25/2/

**Comment by daffl** [comment]
I'm not sure if this is a bug. In your case `station` is a list with no elements (and therefore truthy). I usually check `length` like `{{#unless stations.length}} {{/unless}}`.

The Mustache spec however says that `{{#stations}}` implicitly iterates if stations is array like. So `{{^stations}}` does the opposite of that (if it is an empty array or falsy).

**Comment by pYr0x** [comment]
if #unless is the opposite of #each, #unless should not iterate through an array and so it is false (by my definition)

as #(section) works like #each, #unless should work like ^(section)

^(section) <=> #(section)
#unless <=> #each

or am i wrong?

**Comment by daffl** [comment]
Unless isn't the opposite of `{{#each}}` it's the opposite of `{{#if}}`. As the [documentation says](http://canjs.com/docs/can.stache.helpers.unless.html):

> Render the block of text if the key's value is falsey.

Your key is `sections` and `sections` is truthy.

**Comment by pYr0x** [comment]
Close
