### ISSUE TITLE
API documentation support for Dash and Velocity

### ISSUE THREAD

**Issue by pYr0x** [bitovi/canjs#1539]
i have found these super helpful programs.
it would be very nice if canjs will be available in thse documentation sets.

[Dash] (http://kapeli.com/dash) for ios
[Velocity](https://velocity.silverlakesoftware.com/) for windows

**Comment by marshallswain** [comment]
Dash docs can already be downloaded in the "User Contributed" section of the "Downloads" pref pane in Dash:
![screen shot 2015-03-22 at 10 18 50 am](https://cloud.githubusercontent.com/assets/128857/6770139/e897d850-d07c-11e4-9098-354613a5003b.png)

![screen shot 2015-03-22 at 10 18 32 am](https://cloud.githubusercontent.com/assets/128857/6770140/0c02d66e-d07d-11e4-8c7b-48a788dc016f.png)

**Comment by marshallswain** [comment]
You can also get the docs onto Dash for iOS by side loading through iTunes.

**Comment by marshallswain** [comment]
As far as I can tell, there's not really a direct way to get user contributed docsets onto iOS.  It seems you have to first install them into a desktop app, then open that app's `Library/Application Support` folder to extract the docs and copy them over.  I've put the CanJS docsets on my Dropbox if you need them: https://www.dropbox.com/sh/msxwpxrudpnv95a/AADjwQRAJNaC19w08Va4TCisa?dl=0

**Comment by justinbmeyer** [comment]
I believe it is available for dash

**Comment by pYr0x** [comment]
thanks @marshallswain for this great overview.
i am using velocity on windows.

on my windows machine, there is no folder for putting the content simply in.
all docsets are stored in 
C:\Users\XXXXXX\AppData\Local\Silverlake Software LLC\Velocity\Docsets\Dash
the content is wrapped into a file called Resources.db

do you have a .docset file?

**Comment by marshallswain** [comment]
The three folders in that dropbox link ARE the .docset files, but when they sync to Dropbox they show up as folders.  Try opening the Dropbox link and right-clicking one of the folders to download it.  I think you'll end up with a zip file., but see what you get when you extract it.

**Comment by marshallswain** [comment]
It doesn't look like Velocity lets you download the user-contributed docsets.  Is that what you are noticing?

**Comment by marshallswain** [comment]
It looks like the .docset file extension is a type of installer that puts the .docset folder into place in the Docsets\Dash folder.  I tried editing Velocity's DocsetLibrary.json file and moving the CanJS.docset folder into place manually, but it resulted in a hard crash when I opened Velocity.  Maybe send off an email to the Velocity developer and ask him how you could use those docsets I've posted above?

**Comment by justinbmeyer** [comment]
If you are interested in ongoing support for Dash or Velocity, can you open an issue in documentjs?  We need to create a [generator](http://documentjs.com/docs/documentjs.generator.html) for these systems.  

This is something that we need community support to accomplish.  I'm not going to prioritize for our development.

**Comment by justinbmeyer** [comment]
Closing, I'll re-open if anyone actively picks it up.
