### ISSUE TITLE
v2.2.0 - The included `global.define` breaks UMD defs in other scripts

### ISSUE THREAD

**Issue by marshallswain** [bitovi/canjs#1544]
In order to use `can.jquery.dev.js` in its current form, I have to delete `window.define`:
```html
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/bower_components/canjs/can.jquery.dev.js"></script>
    <script src="/bower_components/canjs/can.stache.js"></script>
    <script src="/bower_components/canjs/can.map.define.js"></script>
    <script src="/bower_components/canjs/can.map.delegate.js"></script>
    <script src="/bower_components/canjs/can.list.promise.js"></script>
    <script src="/bower_components/canjs/can.list.sort.js"></script>
    <script src="/bower_components/canjs/can.fixture.js"></script>

    <script>delete window.define;</script>

    <script src="/socket.io/socket.io.js"></script>
    <script src="/bower_components/momentjs/min/moment.min.js"></script>
    <script src="/bower_components/accounting.js/accounting.min.js"></script>
    <script src="/bower_components/feathers-websocket-client/dist/feathers-websocket-client.js"></script>
    <script src="/bower_components/canjs-feathers/lib/feathers.js"></script>
```

If not, because `can.jquery.dev.js` includes the following lines:
```js
// Line 26: 
var ourDefine = global.define = function(moduleName, deps, callback){
...
// Line 60: 
global.define.amd = true;
```

This breaks any UMD definitions in libraries loaded after CanJS:
```js
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
      // AMD mode gets run instead of window global stuff, below.
      define(['can/util/can', 'feathers-websocket-client'], factory);
  } else if (typeof exports === 'object') {
      module.exports = factory(require('can/util/can'),  require('feathers-websocket-client'));
  } else if(typeof window !== 'undefined' && root && root.can && root.Feathers.client) {
      // This would run if define.amd wasn't true.
      factory(root.can, root.Feathers.client);
  }
}(this, function (can, feathersClient) {
```

**Comment by matthewp** [comment]
I think we went with `define` as the name because of dojo.  I don't think we can rename it but it should be deleting it itself.

**Comment by marshallswain** [comment]
It's for sure not deleting itself.  The other CanJS plugins are dependent on it being in place.  If I move the delete script up above any of the plugins, they fail with varying errors.  If I move the delete script before loading can.fixture.js:
```html
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/bower_components/canjs/can.jquery.dev.js"></script>
    <script src="/bower_components/canjs/can.stache.js"></script>
    <script src="/bower_components/canjs/can.map.define.js"></script>
    <script src="/bower_components/canjs/can.map.delegate.js"></script>
    <script src="/bower_components/canjs/can.list.promise.js"></script>
    <script src="/bower_components/canjs/can.list.sort.js"></script>

    <script>delete window.define;</script>

    <script src="/bower_components/canjs/can.fixture.js"></script>
```

I get the following error
![screen shot 2015-03-23 at 6 30 17 pm](https://cloud.githubusercontent.com/assets/128857/6793502/dd5aab5c-d18a-11e4-8dbd-45b976954299.png)

**Comment by marshallswain** [comment]
I don't understand why it's dependent on it, when each of the plugins contains the same `/*[global-shim]*/` that creates the define.

**Comment by marshallswain** [comment]
Which is the better practice: loading scripts from a widely-used CDN or bundling them into a larger libs file, say jQuery and CanJS and MomentJS in one file?  My guess would be that bundling would be best for creating an independent app, like a PhoneGap project.  General web apps would probably benefit more from using the CDN, especially once HTTP2 is in place.  Am I off base with my thinking?

**Comment by marshallswain** [comment]
> I don't understand why each plugin is dependent on it, when each contains the same /*[global-shim]*/ that creates the define.

Oh. Probably because it's now missing what appears to be a module cache in `define.modules.`

**Comment by matthewp** [comment]
@marshallswain best practice is not to use the global build :)  I think you might have a point though, deleting `window.define` might break things because it depends on `define.modules`, so we do need to cache modules somewhere.

**Comment by matthewp** [comment]
Created https://github.com/stealjs/steal-tools/issues/200 to discuss fixing this issue.  I think we do need a global but maybe it can't be `define`.

**Comment by daffl** [comment]
This has been fixed via https://github.com/stealjs/steal-tools/pull/201
