### ISSUE TITLE
List.prototype.__set should not assume to create an array for indices out of bounds

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1548]
This line: https://github.com/bitovi/canjs/blob/master/list/list.js#L144 assumes that creating items on a list, out of bounds, should create an array and set that value.

**Comment by pYr0x** [comment]
Is this issue releated to #762 ?

**Comment by alexisabril** [comment]
Hey @pYr0x, that issue was in regards to reading values, this one is a recent bug due to setting values.

**Comment by daffl** [comment]
Both should be fixed in the release I'm working to get out (2.2.1)
