### ISSUE TITLE
component fire inserted event twice with zepto

### ISSUE THREAD

**Issue by ethanchen** [bitovi/canjs#1564]
I find that inserted event fired twice on zepto but jquery once. see the test here:
zepto http://jsfiddle.net/8evocLo2/
jquery http://jsfiddle.net/m27m19bo/

**Comment by justinbmeyer** [comment]
Thanks for reporting.  Taking a look!

**Comment by justinbmeyer** [comment]
This is because `.html` calls `.append` internally, so it's firing twice.
