### ISSUE TITLE
steal specific handling has been removed in 2.2.2 dists

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1577]
Affects older users of steal; new steal users should not be affected as they use the system adapter(I believe).

There are steal specific conditions wrapped in `steal-remove-*` comments. Previously we copied files over to the dist repo(canjs.com), however we currently run them through steal for distribution now. As a result, necessary plumbing such as this: https://github.com/bitovi/canjs/blob/master/view/view.js#L385 is removed: https://github.com/bitovi/canjs.com/blob/master/steal/can/view/view.js#L393

Example shows that the `mustache` extension will never be registered with steal.

**Comment by matthewp** [comment]
There's one I missed.

**Comment by daffl** [comment]
Is this fixed via #1592?

**Comment by matthewp** [comment]
Yep!
