### ISSUE TITLE
Customize downloaded version causes error

### ISSUE THREAD

**Issue by pYr0x** [bitovi/canjs#1605]
i use the customize download page to get my canjs.

if i checked can-core, stache and autorender i get the customised file.

easy example:

```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>

<script type="text/stache" can-autorender id="main" message="Hello World">
    <my-component>
    {{message}}
    </my-component>
</script>


<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.js"></script>
<script src="can.js"></script>
<!--<script src="//canjs.com/release/2.2.4/can.jquery.js"></script>-->
<!--<script src="//canjs.com/release/2.2.4/can.stache.js"></script>-->
<!--<script src="//canjs.com/release/2.2.4/can.autorender.js"></script>-->
</body>
</html>
```

if i open the browser i get an error:

TypeError: window.require is not a function
window.require([moduleName], function (value) {

if i use the can CDN and the file separate, i get no error.

**Update 1**
if i added 
```<script src="//requirejs.org/docs/release/2.1.17/minified/require.js"></script>```
 there is a request for **/can/view/stache/stache.js** but i have used the custom version with in it

![alt text](http://i.imgur.com/fhCWEG6.png "request")

**Update 2**
it turns out that the //canjs.com/release/2.2.4/can.jquery.js is different as downloaded can-core custom file

these lines are missing 

```
/*can@2.2.4#util/event*/
define('can/util/event', [
    'can/util/can',
    'can/event/event'
], function (can) {
    return can;
});
/*can@2.2.4#can*/
define('can/can', [
    'can/util/util',
    'can/control/route/route',
    'can/model/model',
    'can/view/mustache/mustache',
    'can/component/component'
], function (can) {
    return can;
});
/*[global-shim-end]*/
(function (){
    window._define = window.define;
    window.define = window.define.orig;
})();
```

**Update 3**
if i added these lines manually to the custom canjs. the test-page will work.
BUT if i added requireJS also to the page. i get an error 
```
Error: Module name "can/view/stache/stache" has not been loaded yet for context: _. Use require([]) http://requirejs.org/docs/errors.html#notloaded
```
this also happend with the separate files..

**Comment by daffl** [comment]
We are running the download builder core generated file through some basic tests (see http://bitbuilder.herokuapp.com/demo.html) which seems to work so it must be either Stache or autorender (although I did add autorender standalone tests in #1586).
@matthewp Any idea why this would use `window.require` instead of our define shim?

**Comment by justinbmeyer** [comment]
http://jsbin.com/vuyexa/3

Shows this working with the normal download.  @daffl Is the download builder updated with 2.2.4?

**Comment by justinbmeyer** [comment]
Or maybe the download builder needs to point to an updated StealJS?

**Comment by daffl** [comment]
http://bitbuilder.herokuapp.com/canjs is showing version 2.2.4. steal-tools is pointing to 0.7.1-pre.2. Is that too old?

**Comment by pYr0x** [comment]
@justinbmeyer if you add requirejs to your jsbin the script will fail

**Comment by justinbmeyer** [comment]
@daffl It's older than what we are using to generate CanJS's download.

@pYr0x Yeah, that's fine.  You shouldn't use the download with requirejs.

**Comment by pYr0x** [comment]
@justinbmeyer why that's ok? What's the difference between the separate files and the concatenated file that can be downloaded via the download page

**Comment by matthewp** [comment]
@daffl Yeah that doesn't have the fix to remove the define at the end of the script. We should update that to the latest 0.7.x version (0.7.4 I think).

**Comment by daffl** [comment]
I just updated to 0.8.0 so this should be fixed now. Although we do recommend using the actual AMD version when using and AMD loader like RequireJS. It makes things a lot easier.

**Comment by pYr0x** [comment]
now i used the AMD version... but same problem here. i think i have found the problem.
after using r.js there should no extra request. but defining a module 

```
define(function (require) {
    var $ = require('jquery'),
        can = require('can'),
        foobar = require('app/module3');

    require('can/view/autorender');

});
```
``` require('can/view/autorender'); ``` still request the can/view/stache/stache
this is because my autorender will dependents on stache

```
<script type="text/stache" can-autorender id="main" message="Hello World">
            <my-component>
            {{message}}
            </my-component>
        </script>
```
and stache is not the default template. if i switch to type="text/mustache" the r.js optimization will work correctly and put all together in one file.

so any idea how can i handle this problem?

**Comment by daffl** [comment]
Shouldn't R.js load it already it you require `can/view/stache` explicitly? Then `can.import` should just get that already loaded and optimized version.

```js
define(function (require) {
    var $ = require('jquery'),
        can = require('can'),
        stache = require('can/view/stache'),
        foobar = require('app/module3');

    require('can/view/autorender');

});

**Comment by daffl** [comment]
I am going to close this one. Please reopen if there are still any issues.
