### ISSUE TITLE
CanJS 2.2.4 can.List.replace() incorrect behavior

### ISSUE THREAD

**Issue by Origami30** [bitovi/canjs#1606]
CanJS Version: 2.2.4
JQuery 2.1.1
Short description: When you replace existing can.List with new one and if this new array is equal to the existing can.List from the beginning to the end of new array then can.List will not be replaced.
Example (copy-paste from Chrome console):
```javascript
var ll = new can.List(["aa","bb","cc"]);
undefined
ll
["aa", "bb", "cc"]
ll.replace(["aa","bb"]);
["aa", "bb", "cc"] // ??? shouldn't it be ["aa", "bb"]?
ll
["aa", "bb", "cc"] // check once again
ll.replace(["aa","bb","cc","dd"]); // take the same array with one extra element
["aa", "bb", "cc", "dd"] // OK
ll
["aa", "bb", "cc", "dd"] // Re-check
ll.replace(["aa","bb"]);
["aa", "bb", "cc", "dd"] // ??? shouldn't it be ["aa", "bb"]?
ll
["aa", "bb", "cc", "dd"]
ll.replace(["aa","xx"]);
["aa", "xx"]
ll
["aa", "xx"]
ll.replace([]); // With empty array it works
[]
ll
[]
```
PS! CanJS 2.1.4 was not affected by this issue

**Comment by daffl** [comment]
That is odd since `.replace` just runs `this.splice.apply(this, [0, this.length].concat(can.makeArray(newList || [])));` (see https://github.com/bitovi/canjs/blob/master/list/list.js#L1096).
It seems to not detect the changes properly. If I do `ll.replace(["aa", "something"])` it works as expected.
