### ISSUE TITLE
Create source maps for stache templates

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1608]
As templates become more complex there will be a need to debug them. Source maps allow you to create line/column mapping so that the template appears in your debugger and you can walk through it and see the values of variables.

Since the StealJS stache plugin creates a module for the template, source maps could be supported by adding a `sourceMappingURL=` comment to the end of the module definition.  The value would be the source map, base64 encoded.

To produce source maps we need to know the line and column from the original stache file.  From that we can create mappings to the generated source and append the source map to the module.

**Comment by matthewp** [comment]
This is something very far out as it would require producing code that can be stepped through.

**Comment by justinbmeyer** [comment]
Yeah, this is sorta impossible the way stache currently works.

**Comment by justinbmeyer** [comment]
Lets close this for now and re-open if we ever have a good idea how to make this work.
