### ISSUE TITLE
can.appendChild passed null el

### ISSUE THREAD

**Issue by JustinLove** [bitovi/canjs#1621]
2.2.4, using amd-dev

The required pieces seem to be:

- Component viewModel with null or missing attribute, which is later set to a list
- Attribute used in stache `#each`
- The second time that attribute is set, `Cannot read property 'appendChild' of null`

I traced it back as far as live.js, line 92; masterNodeList has one element, a text node with a parent, but the index check makes the call to element.after substitute [text], which has a parentless node.  element.after passes the parent (null) to appendChild.

Workaround: make the attribute default to an empty array.

Reproduction: http://jsbin.com/misoku/2/edit

**Comment by daffl** [comment]
I think this is the same issue that the #1634 pull request addresses.
