### ISSUE TITLE
Add notice to canjs npm package to use can instead

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1629]
This has confused some people.

**Comment by daffl** [comment]
I think @justinbmeyer added a deprecation message when you install `canjs`.

**Comment by rasjani** [comment]
janimikkonen@RASJani ~/src/mixradio/web/tvapp (upgrade)$ npm install canjs
canjs@2.2.0-alpha.9 node_modules/canjs
janimikkonen@RASJani ~/src/mixradio/web/tvapp (upgrade)$

Latest canjs does not warn about deprecation.

ALSO do note that canjs@2.2.0-alpha.9 does contain  dist/cjs  but can@2.2.4 doesn't so switching to can package will break builds for those who use webpack/browserify etc ..

**Comment by matthewp** [comment]
@rasjani are you sure you don't have a caching problem?  I just installed can@2.2.4 and did get a `dist/cjs`.  Maybe try `npm cache clean`?

**Comment by rasjani** [comment]
Yeah, it was caching issue..

**Comment by daffl** [comment]
Added the NPM deprecation warning to the https://www.npmjs.com/package/canjs package.
