### ISSUE TITLE
Cannot read value of property defined with "get" AND "set" methods 

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1648]
Demo:
http://jsfiddle.net/akagomez/deagovbn/

Problem 1:
Calling `map.attr('foo')` does not return the correct value.

Problem 2:
`foo`'s `get` method is passed the wrong `lastSetVal` after being `map.attr('foo')` is called. 

Problem 3:
When `foo` is bound to, the `get` method doesn't get called at all. 

I created a test that demonstrates the issue here: https://github.com/bitovi/canjs/commit/369ff13614b0463a8596666bee96135c20bf60d0

/cc @daffl @justinbmeyer

**Comment by kylegifford** [comment]
Looks like this is an issue with `set` not saving correctly. If I modify `set` to the following in the demo, it works:

```
set: function (newVal, setVal) {
    console.log('set:', newVal);
    setVal(newVal);
    return newVal; 
}
```

**Comment by akagomez** [comment]
@kylegifford `setVal` is meant for async setting. I don't think that truly addresses the issue.
