### ISSUE TITLE
Define getter is called extra times if can.map.attributes included

### ISSUE THREAD

**Issue by kylegifford** [bitovi/canjs#1665]
When `can.map.attributes` is included, a `can.map.define` getter is called extra times. This was first noticed when adding assertions inside of a getter in tests, but could have side-affects in production code if getters are being called unexpectedly.

Test: https://github.com/bitovi/canjs/commit/fd3f95cac554f1df3c751cb67df71fe3391aa193

To reproduce, run the `can.map.define` tests in isolation (map/define/test.html). The test will pass. Run the full test suite (test/index.html) and the test will not pass.

At least one of the extra getters is called when https://github.com/bitovi/canjs/blob/fd3f95cac554f1df3c751cb67df71fe3391aa193/map/define/define_test.js#L927 is executed.

**Comment by daffl** [comment]
I'm wondering if that is something that needs fixing. The attributes plugin is deprecated and replaced with the define plugin. The only time this is an issue is in the full test suite. Maybe we should just remove the attributes plugin from it.

**Comment by daffl** [comment]
I removed the attribute tests from being included in #1704.
