### ISSUE TITLE
can.List.replace events typo

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1677]
The first events example claims this will be the output... 

```
// 0, set, Adam, Alexis
// 1, set, Ben, Bill
// 0, remove, undefined, ['Alexis', 'Bill']
// 0, add, undefined, ['Adam', 'Ben'] <- Typo
```

In reality it should be this...

```
// 0, set, Adam, Alexis
// 1, set, Ben, Bill
// 0, remove, undefined, ["Alexis", "Bill"]
// 0, add, ["Adam", "Ben"], ["Alexis", "Bill"] <- Correction
```

Per this example: http://jsfiddle.net/akagomez/jfebph4e/

**Comment by rjgotten** [comment]
Interesting: while that *is* what the current code does, does it make sense for the current code to do that in the first place?

If you have a sequence of an add and a remove event where the new value of the remove event is `undefined`, then shouldn't the old value of the add event that logically happens *afterwards* also be `undefined`?

**Comment by akagomez** [comment]
@rjgotten That seems logical to me also. 

@justinbmeyer @daffl Is there a specific reason why `oldVal` isn't `undefined` in `can.list.prototype.splice` when the `add` event is fired? 

```
if (howMany > 0) {
	// tears down bubbling
	bubble.removeMany(this, removed);
	this._triggerChange("" + index, "remove", undefined, removed);
}
if (args.length > 2) {
	// make added items bubble to this list
	for (i = 0, len = added.length; i < len; i++) {
		bubble.set(this, i, added[i]);
	}
	this._triggerChange("" + index, "add", added, removed);
}
```
https://github.com/bitovi/canjs/blob/master/list/list.js#L340

**Comment by alexisabril** [comment]
@rjgotten I'm going to rephrase your thought a bit, but correct me if I'm wrong.

A confusing note is that this example is listening to the "change" event, which has new and old values passed as arguments. However, "remove" only passes elements that have been removed in the event, in the place of the old values argument.

```
var list = new can.List(['a']);

list.bind('change', function(o, ev, type, val, old) {
  console.log(type, { new: val, old: old });
});

list.replace(['b']);

//console output
//"remove" does not have any new elements added to this collection, as such is undefined
//remove { new: undefined, old: ['a'] }
//"add" does have new elements adding to this collection
//add { new: ['b'], old: ['a'] }
```

**Comment by justinbmeyer** [comment]
Seems like the docs have it right, but the code has it wrong.  The `oldVal` argument with an "add" event should probably be `undefined`.
