### ISSUE TITLE
Define plugin type compute needs to be documented

### ISSUE THREAD

**Issue by daffl** [bitovi/canjs#1690]
Setting `{ type: 'compute' }` which has been implemented in https://github.com/bitovi/canjs/commit/eeeb107f44f64b7404b9f22005589306e2418111 for https://github.com/bitovi/canjs/issues/1409 is not documented in https://github.com/bitovi/canjs/blob/master/map/define/doc/type.md

**Comment by akagomez** [comment]
For reference, there's a bit of documentation in the original PR: https://github.com/bitovi/canjs/pull/1486.
