### ISSUE TITLE
Ability to delegate "inserted", "removed" and "attributes" events

### ISSUE THREAD

**Issue by isadovskiy** [bitovi/canjs#1695]
It would be great to have more control on "inserted", "removed" and "attributes" events by introducing ability to delegate them.

Please check fiddle: http://jsfiddle.net/cs725u9e/9/

Would be great if can.Component and can.Control allow to listen for inserted/removed/attributes events on their children elements:

can.Control.extend({
  ".item inserted": function(el, ev){
      ....
  }
})

can.Component.extend({
  tag: "my-component",
  events:{
    ".item inserted": function(el, ev){
        ....
    }
})

**Comment by justinbmeyer** [comment]
I wont add this for performance reasons.  Every single inserted element would have to have an event triggered on it that bubbles up to the document.

If you need this, describe a way to make MutationObservers work with can.Component.
