### ISSUE TITLE
Sort plugin excludes batchNum; Maybe fires unnecessary events

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1707]
```
can.batch.start();
listB.push({ id: 'a' });
listB.push({ id: 'a' });
listB.push({ id: 'a' });
can.batch.stop();
```

```
"// BATCHED; SORTED..."
"    Sorted..." // <-- Upon creating the list
"    Sorted..." 
["type:", "length", "batchNum:", undefined]
["type:", "length", "batchNum:", 9] // <-- This event caused the sort
"    Swapped? 1, 2"
["type:", "length", "batchNum:", undefined]
["type:", "length", "batchNum:", 9] // <-- This event caused the swap
["type:", "length", "batchNum:", 9]
```

The Sort plugin fires events like `length`, `add`, `reset`, etc. for `can.view.live.list` and does nothing to pass along the original `batchNum` that instigated the work. 

Since the current Sort plugin is derived from the previously incomplete Sort plugin, those events were left in/adapted. I'm curious to know if we can do without them all together. 

http://jsbin.com/poduxa/6/edit?js,console

**Comment by daffl** [comment]
Closed via #1718
