### ISSUE TITLE
Unable to load canjs in node.js environment

### ISSUE THREAD

**Issue by Luanre** [bitovi/canjs#1711]
CanJS 2.2.6

I tried to load canjs using the code:
```javascript
var can = require('can/dist/cjs/can');
```
But I've met the exception:
```shell
./node_modules/can/dist/cjs/compute/get_value_and_bind.js:23
can.__isRecordingObserves = function () {
  ^
ReferenceError: can is not defined
```

I've found that `get_value_and_bind.js` requires '../util/util.js' but doesn't save result to `var can`.

**Comment by justinbmeyer** [comment]
Thanks.  This will be fixed in the next release.

**Comment by justinbmeyer** [comment]
Btw, are you using browserify? Which version?  With latest, you should only have to write:

```
require('can')
```

**Comment by Luanre** [comment]
No, I'm setting up unit-test environment to test my components' scope methods.

I used `browserify` before and yes, canjs could be included using:
```javascript
var can = require('can');
```
But for plugins you still need to write:
```javascript
require('can/dist/cjs/object/object');
```

**Comment by Bajix** [comment]
Do you think you could supplement this with an example on how to load CanJS within NodeJS?

This isn't working for me, nor does loading it with StealJS. This issue doesn't appear resolved at the moment
