### ISSUE TITLE
Observable promises is not documented

### ISSUE THREAD

**Issue by pYr0x** [bitovi/canjs#1729]
since promises are observable, on the API doc there is no documentation.
http://canjs.com/docs/can.stache.html

**Comment by pYr0x** [comment]
push ! no documentation of observable promises !

**Comment by daffl** [comment]
@justinbmeyer this has indeed been added in #1540 but was never documented. I will add a `promise.md` that talks about how to use it.

**Comment by justinbmeyer** [comment]
How exactly would this be documented?

**Comment by marshallswain** [comment]
The 2.2 blog article is a good start. 
http://blog.bitovi.com/canjs-2-2/
