### ISSUE TITLE
CanJS recipes/tutorials/examples link broken

### ISSUE THREAD

**Issue by juliusakula** [bitovi/canjs#1736]
The first link on [this page](https://github.com/bitovi/canjs/wiki/CanJS-blog-posts,-tutorials,-and-examples) (first google hit for "canjs example project github") links to http://canjs.com/recipes.html, which returns a 404 error. I'm looking for examples and recipes, I believe I found them at http://canjs.com/guides/Recipes.html - is that correct?

**Comment by daffl** [comment]
It is indeed, thank you for pointing that out. I fixed the link.
