### ISSUE TITLE
Can-Value not included in version 3.3

### ISSUE THREAD

**Issue by gazlu** [bitovi/canjs#1737]
Can/View does not have binding and hence no can-value attr.

Is it removed from 3.3? please help me with alternative

**Comment by kkkdb** [comment]
None yet

**Comment by matthewp** [comment]
Do you mean 2.3-pre?  There is no 3.3.

**Comment by gazlu** [comment]
There is I just pulled it. I tried also downloading zip ball from http://www.javascriptmvc.com/dist/javascriptmvc-3.3.zip butno luck.

**Comment by gazlu** [comment]
ohhh you mean canjs version, got it

**Comment by matthewp** [comment]
Oh, you meant JavaScript MVC 3.3.  No, can-value (or any other can/view/bindings) is not part of JMVC 3.3.  You probably want to upgrade to CanJS 2.2.

**Comment by gazlu** [comment]
ok, thanks.
