### ISSUE TITLE
canjs backup does not report correct "isDirty" status after modifications were made

### ISSUE THREAD

**Issue by WooFerPPK** [bitovi/canjs#1742]
Please see this example here: http://jsfiddle.net/fsw49seo/

When trying to create a new can.map object, add data, and then use backup, the 'isDirty' status will return false even though I have since modified the object. My example above shows a few attempts to get the status of the object, even after modifying it.

**Comment by alexisabril** [comment]
Hey @WooFerPPK, you need to pass the optional [deep] bool to isDirty as you're checking for nested changes: http://canjs.com/docs/can.Map.backup.prototype.isDirty.html

Adding .isDirty(true) to your test makes it work as you would expect.
