### ISSUE TITLE
can.List filter should return lists of the same type

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1744]
https://github.com/bitovi/canjs/blob/master/list/list.js#L1102

should be

https://github.com/bitovi/canjs/blob/master/map/list/list.js#L5

**Comment by alexisabril** [comment]
This is true with other list helper methods such as reverse()

**Comment by justinbmeyer** [comment]
@daffl @alexisabril if this is in minor should we close it?  I'm ok closing minor related things.

**Comment by daffl** [comment]
Yes, this is closed.
