### ISSUE TITLE
Switching to the 1.1 docs and back to 2.2 sets an incorrect url

### ISSUE THREAD

**Issue by alexisabril** [bitovi/canjs#1757]
On the CanJS API docs:

- default url: http://canjs.com/docs/index.html with v2.2
- select 1.1 from the dropdown, new url: http://canjs.com/1.1/docs/index.html (dropdown shows 2.0)
- select 2.2 from the dropdown, new url with a 404: http://canjs.com/2.2/1.1/docs/index.html

**Comment by daffl** [comment]
Just verified that this is fixed.
