### ISSUE TITLE
Preloaded mustache template not working with observables.

### ISSUE THREAD

**Issue by notdang** [bitovi/canjs#1761]
Here is the fiddle: http://jsfiddle.net/hse9nxo8/1/

I see @@!!@@ instead of the values.
Am I doing something wrong?

**Comment by pYr0x** [comment]
Mustache will be deprecated .. Please use stache instead.

**Comment by daffl** [comment]
Also, how does the original template look like?

**Comment by notdang** [comment]
It used to be a form, and I simplified it down to a span with an input, and got the same result as in the fiddle. When being used in development mode (template being loaded via an async call), the live binding works. But for production, I am using can-compile to precompile/preload the templates and it doesn't work. 
I couldn't find a solution to this, so I switched to stache and got it working in both development and production mode. 
I think I can lose the issue, since I got it working with stache and mustache will be deprecated.
