### ISSUE TITLE
can.Component vs can.Control

### ISSUE THREAD

**Issue by jawshooah** [bitovi/canjs#1772]
After reading the documentation, I'm still a bit confused as to when I should use `can.Component` instead of `can.Control`.

It seems that `can.Control` gives me more freedom to define dynamic behavior, whereas `can.Component` is more useful for common static UI components. It has event handlers, yes, but there doesn't seem to be a way to customize behavior per-instance.

For example, I can create a `can.Control` for modal dialogs that allows each instance to behave differently:

```javascript
var Modal = can.Control.extend({
  defaults: {
    templatePath: './modal.ejs',
    message: 'Hello World',
    onOpen: null,
    onClose: null
  }
}, {
  init: function() {
    this.updateView();
  },
  update: function() {
    this.updateView();
  },
  updateView: function() {
    $(this.element).html(can.view(this.options.templatePath, this.options));
  },
  openDialog: function() {
    // ...
    if (typeof this.options.onOpen === 'function') {
      this.options.onOpen();
    }
  },
  closeDialog: function() {
    // ...
    if (typeof this.options.onClose === 'function') {
      this.options.onClose();
    }
  },
  "button.close click": function(_, ev) {
    ev.preventDefault();
    this.closeDialog();
  }
});

var myModal = new Modal('#my-modal', {
  message: 'Custom Message',
  onOpen: function() {
    console.log('Modal opened');
  },
  onClose: function() {
    console.log('Modal closed');
  }
});
```

Is there a way to achieve similar behavior with `can.Component`?

**Comment by matthewp** [comment]
Good question, with Component's you don't instantiate them, they are instantiated automatically as Stache runs your template.  So for that reason you can't pass functions into Components.  A lot of people have wanted a way to do this but we just haven't come up with the "right" solution yet. Here's an issue about it: https://github.com/bitovi/canjs/issues/1209

As far as your question about what is the difference... Controls are a bit lower level and are useful for when Components are not appropriate, for example if you need mixin-type behavior pairing a Control with a can.view.attr is a good way to go. Controls are also a better choice when you have performance critical parts of your app.

**Comment by jawshooah** [comment]
Gotcha, so I was right in thinking that Controls are more flexible in terms of behavior.

The equivalent of `this.options` for a Component would be `this.viewModel`, right? And any attributes set on the top-level element become members of that object?

**Comment by justinbmeyer** [comment]
I'd say you should be using components 90% of the time.

**Comment by jawshooah** [comment]
@justinbmeyer The app I'm working on currently has a lot of Controls that interact with each other. How could one Component interact with (e.g. invoke a method of) another?

**Comment by justinbmeyer** [comment]
They typically don't invoke methods on each other, instead they change each other's state.  After all, when a method is invoked, I'm betting you are changing state.

Using components requires changing how you think to a less functional and more state-based approach (which is much better for testing and correctness).

For example, I might have a modal with a "visible" state like:

```
<my-modal visible>
```

A parent component can connect to it and toggle it with it's own state like:


```
<my-parent>
  <button can-click="{saveItem}">Save</button>
  <my-modal {{#showingModal}}visible{{/showingModal}}>
    Are you sure?
    <a can-click="{hide}">X</a>
  </my-modal>
</my-parent>
```

```js
can.Component.extend({
  tag: "my-parent",
  viewModel: {
    saveItem: function(){
      this.attr("showingModal", true)
    }
  }
});

can.Component.extend({
  tag: "my-modal",
  viewModel: {
    define: {
      visible: {
        type: "htmlbool"
      }
    },
    hide: function(){
      this.attr("visible", false)
    }
  }
});
```

(closing b/c this isn't a bug, but feel free to keep asking questions related to this topic here).

**Comment by mickmcgrath13** [comment]
What are some use cases for using a Control over a Component (You mentioned that we should be using components 90% of the time;  What is the other 10% for)?

**Comment by gsmeets** [comment]
There's a few things. My root elements are still controllers, because I don't think you can instantiate components from code. (If someone can prove me wrong here would be nice, still looking for a way to get rid of some semi-superfluous controllers).

Other things that come to mind is when you render html server-side and you're just adding some behaviour over the existing dom nodes.

**Comment by mickmcgrath13** [comment]
Of course, if you're rendering html server-side, there might be a better way to approach the situation anyway ;)

**Comment by justinbmeyer** [comment]
@mickmcgrath13 I will often use a `can.view.tag` or `can.view.attr` to setup a `can.Control` for things that extend the DOM in some way.

For example @cklanac had some functionality where once an item was scrolled into view, it would mark itself as read.

One way to accomplish this would be to let user add a `visible-able` attribute on any element and register event handlers on any children you want to know when they have been scrolled into view:

```
<ul visible-able>
  <li (visible)="{markAsRead}">
  <li (visible)="{markAsRead}">
```

> (visible) is the same as writing can-visible

I would implement this something like:

```
Visibleable = can.Control.extend({
  "scroll": function(){
    ... figure out what just became visible ... 
   newVisibleElements.trigger("visible")
  }
});

can.view.attr("visible-able", function(element){
  new Visibleable(element)
})
```
I still mostly use templates to wire things up.  I just use controls for low-level things like this.

**Comment by mickmcgrath13** [comment]
That helps a lot, thanks!
