### ISSUE TITLE
can.map throws strings, not errors. 

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1773]
Currently:

```
throw "can.Map: Object does not exist";
```

Should be: 

```
throw Error("can.Map: Object does not exist");
```

https://github.com/bitovi/canjs/blob/master/map/map.js#L495

/cc @imjoshdean

**Comment by imjoshdean** [comment]
:+1: Throwing strings don't provide things like stack traces and other Error goodies that are useful.

**Comment by daffl** [comment]
:+1: But I'm wondering if this could be considered a breaking API change?

**Comment by akagomez** [comment]
Other instances I found: 

```
./map/define/define_test.js:546:						throw '"foo"\'s value method should not be called.';
./map/lazy/lazy.js:196:				throw "can.LazyMap: object does not exist";
./map/map.js:495:						throw "can.Map: Object does not exist";
./util/fixture/fixture.js:108:					throw "fixtures.js Error " + error + " " + message;
./view/parser/parser.js:236:				throw "Parse Error: " + html;
./view/view.js:46:			throw "can.view: No template or empty template:" + url;
```

**Comment by imjoshdean** [comment]
I...don't think so? How would it break the API?

**Comment by justinbmeyer** [comment]
It would not.  We don't document these errors.

**Comment by daffl** [comment]
Shouldn't it be `throw new Error("can.Map: Object does not exist");`? Anyway, if it doesn't we can even get it into the 2.2.7 patch release.

**Comment by justinbmeyer** [comment]
@akagomez can you submit a pull request for this?  Thanks!

**Comment by imjoshdean** [comment]
@justinbmeyer I'm submitting one shortly.

**Comment by akagomez** [comment]
The PR: #1811
