### ISSUE TITLE
can.Component with stache template has a memory leak if a content tag is used

### ISSUE THREAD

**Issue by gsmeets** [bitovi/canjs#1774]
When I use a can.Component with a stache template that has a content tag, then a mem leak occurs. If I remove the can.stache() behind the template definition the content tag actually stops working (i.e. "test4" does not appear in the page), I thought this was also supported in mustache. 

Repro code below, the can.custom build is the current one ffom the site, with the stache plugin added. Using the latest 1.11 jquery version as well here. 

	<!DOCTYPE html>
	<html lang="nl">
	<head>
		<title>Tests</title>
		<meta charset="utf-8">

		<script src="/Scripts/1.0.0.0/lib/jquery/jquery-1.11.3.js"></script>
		<script src="/Scripts/1.0.0.0/lib/can.custom.js"></script>

		<script>

			( function () {
				can.Component.extend( {
					tag: "mem-leak",
					template: can.stache("<p>test3<content /></p>")
				} );

				var template = can.stache( "<mem-leak>test4</mem-leak>" );

				$( document ).one( "click", function () {

					$( "div" ).append( template( { test: "test2" }, {} ) );

					$( document ).one( "click", function () {
						$( "div" ).empty();
					} );
				} );
			} )()
		</script>
	</head>
	<body>
		<div>test</div>
	</body>
	</html>

**Comment by justinbmeyer** [comment]
Can you create a test like the ones listed here:

https://github.com/bitovi/canjs/blob/master/component/component_test.js#L1519

https://github.com/bitovi/canjs/blob/master/component/component_test.js#L1562

https://github.com/bitovi/canjs/blob/master/component/component_test.js#L1612

These test potential memory leaks around <content>

**Comment by gsmeets** [comment]
Those tests won't work. The dom nodes are detached, so they're not reachable from code. That means they're not available through the can.view.nodeLists. 

I've done some more testing, and it seems I'm getting 1 leaking document fragment per component that has a content tag. And all the contents in it leaks as well. 

Doesn't matter if I instantiate them once of a million times. Luckily that means the problem is less severe than I thought. :)

**Comment by justinbmeyer** [comment]
Can you attach them? There is almost always a way to sniff out a memory leak.

**Comment by justinbmeyer** [comment]
@gsmeets anyway you can make a test?  Thanks!

**Comment by justinbmeyer** [comment]
Is it possible you are looking at the document fragment and elements created and used by the templates?

I can't seem to identify any other elements besides those.

**Comment by justinbmeyer** [comment]
Changing the test to:

```
<!DOCTYPE html>
<html>
<head>
   
</head>
<body>
    <div>test</div>
     <script src="../../node_modules/steal/steal.js" main="@empty"></script>

    <script>

        steal("can/component","can/view/stache", function () {
            can.Component.extend( {
                tag: "mem-leak",
                template: can.stache("<p>test3<content /></p>")
            } );


           

            $( document ).one( "click", function () {

	
				for(var i = 0; i < 1000; i++) {
					var template = can.stache( "<mem-leak>test4<label>abc</label></mem-leak>" );
               		$( "div" ).append( template( { test: "test2" }, {} ) );
				}
				

                $( document ).one( "click", function () {
                    $( "div" ).empty();
                } );
            } );
        } );
    </script>
</body>
</html>
```

I see:

<img width="587" alt="cursor_and_tests" src="https://cloud.githubusercontent.com/assets/78602/8924085/f31cc488-34be-11e5-8c47-c936ab0f5ef0.png">


Which is what I expect.  So it doesn't seem like there is a leak.
