### ISSUE TITLE
View-only "attributes" without binding in templates

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1776]
Sometime models/maps object may also contain attributes with static (for example string) data, that is not supposed to change during app lifecycle.

When such attributes are used in stache templates unnesessary bindings are created. I think this can affect perfomance in some way, is it possible to get rid of such exessive bindings in templates? Or it is not woth to bother about it?

**Comment by justinbmeyer** [comment]
Are you sure bindings are setup? I can't think of a mechanism that would do this. Afaik, static values don't call can.__observe.

**Comment by whitecolor** [comment]
I mean static values not they are not set up as:

`map.prop = 1` (vs attr set: `map.attr('prop', 1), but this properties come from server for example, but they are not supposed to change, but they are still are treated as map's attributes and are subjects for change event.

**Comment by gsmeets** [comment]
I have the same issue. I'm pulling some data from the server for some sort of logging timeline, and it generates 7K cid's (compared to 2.5K from the rest of the page) while it doesn't have to be live at all. Was wondering the same thing as whitecolor.

**Comment by justinbmeyer** [comment]
You can use the define plugin. type: "*"

**Comment by whitecolor** [comment]
```
var Person = can.Map.extend({

  define: {
     age: {
       type: 'number'
       value: 10
     }
     name: {
        type: '*',
        value: {
           first: '',
           last: ''
        }
       
     }
  }

})
```

in this example `last` and `first` props of `name` wont have bindings as name is plain object. but `name` it self and `age` still will have bindings. An I want this props to be out of live binding. But I a may want some other props be live binded so I have to use can.Map, not simple object or can.Construct for 'Person' class.

**Comment by justinbmeyer** [comment]
@whitecolor you can't have nested type definitions inside something with type: "*".  So:

```
name: {
        type: '*',
        value: {
           first: '',
           last: ''
        }

     }
```

wont work.  The reason is that a map needs to be created for things like default properties to work in the first place.

However, you can setup the object yourself in a setter:

```
name: {
  type: '*',
  set: function(nameObj){
    nameObj.first = nameObj.first || "";
    ...
    return nameObj;
  }
}
```

closing b/c "*" should provide a good enough solution for most of these problems.

**Comment by whitecolor** [comment]
why this wont work?

```javascript
     name: {
        type: '*',
        value: {
           first: '',
           last: ''
        }

     }
```
name will be plain object `{fist: '', last:''}`

`'*'` can only prevent live bindings for "nested" properties like in this case `name.first`, but it can not prevent live binding of `name` property it self ofr `age` property that are directly on can.Map instance.

**Comment by justinbmeyer** [comment]
I miss-read your code.  That should work, but that `{first: '', last: ''}`object would be shared by every instance of that map.  

What do you mean by:

> An I want this props to be out of live binding. But I a may want some other props be live binded so I have to use can.Map, not simple object or can.Construct for 'Person' class.

what is  "this propos"?



> '*' can only prevent live bindings for "nested" properties like in this case {{name.first}}, but it can not prevent live binding of {{name}} property it self or {{age}} property that are directly on can.Map instance.

Yes, that is correct.  But I think that creating a binding of name or age is fine.  Otherwise, don't create a map in the first place if you don't want all 1st level properties to have bindings.

The only other alternative is to create a stache helper that prevents binding:

```
{{~"age"}}
```

```js
can.stache.registerHelper("~",function(prop, options){
  return options.context[prop]
})
```

**Comment by whitecolor** [comment]
ok helper would work.

**Comment by whitecolor** [comment]
Why not include it in core? Could be useful.

**Comment by justinbmeyer** [comment]
Because live-binding is often less expensive then creating the observables. You aren't probably saving much time with this.
