### ISSUE TITLE
Accessing the fully qualified binding name

### ISSUE THREAD

**Issue by gsmeets** [bitovi/canjs#1781]
Consider this template

    {{#each foo.items}}
        <my-component some-property='{bar}' />
    {{/}}

Now, in my component I'd like somehow to know what the full indexing path from the root model is to my bar property. i.e. I want to find `foo.items.0.bar` for the first item in the list, and `foo.items.1.bar` for the second, etc.

Is there any way to retrieve this information currently? The only way to get this done seems to be to overwrite the each helper and inject some metadata into that. If so, is this something that you're willing to include in the codebase, or is this something I'll have to maintain myself separately?

**Comment by matthewp** [comment]
There's an `@index` helper you can use:

```handlebars
{{#each foo.items}}
    <my-component property-index="{@index}" some-property='{bar}' />
{{/each}}
```

**Comment by gsmeets** [comment]
But at that point I still don't know I accessed foo.items

**Comment by matthewp** [comment]
You can create a helper that passes in the string "foo.items.0.bar" if that's what you're going for.  What is the use-case that a component needs to know the parent's data structure?

**Comment by gsmeets** [comment]
Validation. 

Just prior to submitting the form the entire root model is recursively validated. Individual components are bound to submodels. What I'm currently doing is re-evaluating every component individually as well, if I detected some error, but that's not that clean of a solution.

**Comment by justinbmeyer** [comment]
Currently, there's no way of doing this.  It might be possible to create a scope with a property.  For example:

```js
new can.view.Scope( child, parent, "foo")
```

This would mean `child` is the `foo` property of `parent`.

However, this is going to get more complex with indexes which change.  You might be able to get the "@index", but it would be tricky.

> Just prior to submitting the form the entire root model is recursively validated. Individual components are bound to submodels. What I'm currently doing is re-evaluating every component individually as well, if I detected some error, but that's not that clean of a solution.

Why are you "evaluating" components?  Typically, validation can be done in the model layer and has nothing to do with a component.  Could this be done?  If not, can you go into detail how and why you are doing validation the way it is being done?  Thanks.

**Comment by gsmeets** [comment]
I have a component of the form:

    <text-editor binding="{someModel.prop}" />

This component includes a label, a text input and an error message if the bound property is in an invalid state.

Right now I check at a top level if some part of my model is in a state of error, if that's the case I message all the child components to re-evaluate if they're in an error state. At that point each component validates the bound property again against its local model. Effectively this is doing validation twice. That's why I was thinking along the lines I've posted in my initial post.

If you have some ideas on how to this in a better way I'm happy to hear it.

**Comment by rjgotten** [comment]
> If you have some ideas on how to this in a better way I'm happy to hear it.

Create some form of bindable errors metadata-collection on the model and bind to that in your component. Update that collection of error metadata as part of a validation process that flows down the tree of the model hierarchy.

That way you avoid having to look up hard attribute names containing the full descending paths through the model tree.

And if you're going to construct your own errors metadata, you want just want to go for broke and also create warning states as well, which is a rather big hole in the current state of model validation for such scenarios as reporting on possibly invalid e-mail addresses or possibly weak password strength in tandem with actual errors.

**Comment by gsmeets** [comment]
That won't work for my use case unfortunately. I have pretty highlevel components bound to some random part of the viewmodel. This allows me to have templates that non-programmers, heck even non-ux-designers can understand. That does put me in the position that the same binding is used for the validation.

I'll just stick to what I've got now, validation isn't something that occurs a lot, so the extra perf hit is acceptable.

**Comment by justinbmeyer** [comment]
@gsmeets @Macrofig has been working on validations / error handling in CanJS.

Your use case is needs some feature that I've been thinking about for a while, but never had a use case.  Thanks for giving me one!

I think the solution to your problem is the ability to create a compute for a map attribute that will also contain any errors associated with that map attribute.

For instance, say I could do something like:

```js
Person = can.Map.extend({
  define: {
    name: {
      validate: {
        required: true
      }
    }
  }
});

var dude = new Person();
dude.attr('errors') //=> {name: ["name is required"]}
```

I'd like to be able to create a compute that includes `name`'s errors:

```
name = dude.compute('name');

name() //-> undefined
name.errors() //-> ["name is required"]
name("Guido");
name.errors() //-> []
```

With this, errors can exist with the value of a compute.  I think there's an issue for this.  I'll try to find it.

**Comment by justinbmeyer** [comment]
This was the issue: #173

**Comment by justinbmeyer** [comment]
keeping this issue closed.  I might reopen 173.
