### ISSUE TITLE
Parent helpers inside helper

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1783]
I need to create helper that will return template stache fragment and insert it in DOM, so I do:

```javascript
helpers: {
    someTemplateHelper: function(options){
            var template = '<my-comp"></my-comp>'
            return can.stache(template)(options.contexts)
    }
}
```

The parent context are passed to stache fragment, but not helpers (`options` do not contain `helpers`). Is it possible to access parent helpers and render template that can access them?

**Comment by matthewp** [comment]
Could probably be [added here](https://github.com/bitovi/canjs/blob/master/view/stache/mustache_core.js#L299)

**Comment by whitecolor** [comment]
Yes this works if we do:

```
				can.simpleExtend(helperOptions, {
					context: context,
					scope: scope,
					contexts: scope,
					hash: hash,
					nodeList: nodeList,
					exprData: exprData,
					helpers: options // added here
				});
```

An then we can do:
``
return can.stache(template)(options.contexts, options.helpers)
```

Should it be done this way? or add:

```
options: options
```

**Comment by matthewp** [comment]
Doesn't options contain more than just helpers?  If so I think options is what it should be called.

**Comment by whitecolor** [comment]
well its structure is:

```
__cache: ..
__context: {
   helpers: ..
   tags: ...
 }
_parent: ..
```

It is better look yourself.

**Comment by whitecolor** [comment]
Maybe @justinbmeyer can advice what better to do with this issue?

**Comment by whitecolor** [comment]
@justinbmeyer have you seen that?

**Comment by whitecolor** [comment]
@matthewp any comment on that?

**Comment by justinbmeyer** [comment]
I think we should call it helperOptions.  And update our docs to call these objects helperOptions everywhere.

**Comment by justinbmeyer** [comment]
It does contain more then helpers.  I really don't have a good name for this.  For now, we might pass it as `helpers` and `options` but don't document it until 3.0.  With 3.0 we need to decide what the names of these things are.  Personally, I'm not sure the "helpers" should even exist.  It should just be something on the root of every template ... but on the normal scope chain.  No reason to have 2.

**Comment by whitecolor** [comment]
@justinbmeyer So what would be right code to add at https://github.com/bitovi/canjs/blob/master/view/stache/mustache_core.js#L306 ?

**Comment by matthewp** [comment]
Pass it as both.

```js
options: options,
helpers: options
```

**Comment by asavoy** [comment]
+1 I've run into this as well

**Comment by whitecolor** [comment]
pull this to master or minor?
