### ISSUE TITLE
Make promises observable

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#179]
[VOTE HERE](http://bithub.com/event/25912)
```
{{#Todo.findAll}}
  <li>
    {{name}}
  </li>
{{/}}
```

**Comment by matthewp** [comment]
It will be good to have a way to know when a template is "done", after all promises have been resolved.

**Comment by justinbmeyer** [comment]
You can always wire that up yourself with `can-inserted` like:

```
{{#if promise.isRejected}}<span class='rejected' can-inserted="{doSomething}">{{promise.reason.message}}</span>{{/if}}
```

**Comment by matthewp** [comment]
I'm thinking of the server rendering use-case, would want something more generic.

**Comment by daffl** [comment]
I think we can close this, Observable promises made it into 2.2.
