### ISSUE TITLE
selective scopeLeak

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1797]
scopeLeak allows to protect (or make private) all the attributes of the scope (viewModel), it would be usefull to be able to make private only certain attributes or in reverse allow only certain attributes leak (this would be more controllable behaviour).

**Comment by justinbmeyer** [comment]
This isn't possible given how scope currently works.  Either something is in scope or it is not.  Anything in the scope can be accessed.

So, there's not a way to put a viewModel in the scope, but only have certain parts accessible. 

Is there a specific use case you have for this?

Also, what would this look like?

**Comment by whitecolor** [comment]
Well currently one should think more about names conficts. ability to allow only specific attributes to be propagated would be valuable I think. Specific scopes for members (private, protected, public) have sense in many languages. I think here simplified version is needed.

**Comment by justinbmeyer** [comment]
@whitecolor thanks for your suggestion.  

Preventing scope from leaking, especially when used with [#REFERENCE attributes](http://canjs.com/2.3-pre/docs/can.view.bindings.reference.html) does "allow only specific attributes to be propagated". 

Unfortunately, without a use case or a proposed API, this isn't going to be a priority.  If this is something you'd like to see land in the framework, please create a proposed API to enable this.  Thanks!

**Comment by whitecolor** [comment]
@justinbmeyer Yes you are right with reference it is possible to implement my scenario. I will try I say if my proposal is still seem to be valuable. In general does preventing scope leaking tend to improve performance?

**Comment by justinbmeyer** [comment]
> In general, does preventing scope leaking tend to improve performance?

Not really.  I've never seen scope lookup be the dominate part of rendering.  I suppose it could be expensive if you had a lot of lookups for values that were initially undefined.

**Comment by justinbmeyer** [comment]
I'm closing this for now for lack of a specific proposal.

**Comment by whitecolor** [comment]
I think it is still valueable to allo only certain component's scope attrs (or methods) to be leaked outside. I have a general purpose components where for example only one property have to be available in child scope, but I have to have all props leaked and it may cause some conflicts.

**Comment by dylanrtt** [comment]
> I have a general purpose components where for example only one property have to be available in child scope, but I have to have all props leaked and it may cause some conflicts.

@whitecolor I can certainly relate to this but using the reference scope with `leakScope: false` is working great for me so far. It's actually become pretty central to how I write components. Consider this example:

```html
<my-dialog {^.}="*dialogApi">
  // stuff
  <input type="button" value="Close" ($click)="*dialogApi@close()">
</my-dialog>
```

or even this:

```html
<my-dialog {^@close}="*closeDialog">
  // stuff
  <input type="button" value="Close" ($click)="*closeDialog()">
</my-dialog>
```

I understand you are waiting to upgrade until another issue is fixed but I would definitely give this a try when you do because it allows you to have 0 leakage which I think is even better than selective leakage.

Is there a use case where the references scope would not solve your problem?

**Comment by whitecolor** [comment]
@dylanrtt ok thanks) It seems new binding syntax is very flexible
