### ISSUE TITLE
Destroyed models not automatically removed from can.Model.List

### ISSUE THREAD

**Issue by canac** [bitovi/canjs#1804]
The can.Model.List documentation says, "When you destroy a model, if it is in that list, it will automatically be removed from the list." However, this is not working for me. For example in the following code, it reports that there are still three items in the list, when there should only be two ([JSFiddle](http://jsfiddle.net/calebcox314/xm2v2w3x/)).
```javascript
var Model = can.Model.extend('Model', {
    destroy: function(id, params, success, error) {
        return jQuery.Deferred().resolve({}).promise();
    }
}, {});

var list = new Model.List([new Model({ id: 1 }), new Model({ id: 2 }), new Model({ id: 3 })]);
list.attr('0').destroy().then(function() {
    alert('There are ' + list.length + ' models in the list');
});
```
However, if I call `list.bind('remove', function() {});` immediately after creating the list, it reports that there are two models in the list, just as expected. I am not familiar with the CanJS code base, but in my preliminary debugging, it looks like in the first case, the bubble rules are not being set up for the model list.

**Comment by justinbmeyer** [comment]
This behavior is only added when the list is bound to. Otherwise a memory leak would be present. 

This isn't a bug. 

In an app, you would almost always bond to the list. If you use templates to render it, it is being bound to.

**Comment by justinbmeyer** [comment]
Closing, let me know if this makes sense.

**Comment by canac** [comment]
Yes, that makes sense, thank you for clarifying. I hadn't thought about the possibility of memory leaks with this feature. You might consider tweaking the documentation to prevent other people from becoming confused about this feature like I was.
