### ISSUE TITLE
map.define default behavior options work only for defined attributes

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1814]
map.define default behavior works only for defined:

```
define:{
  
   '*': {serialize: false}
},
someAttr: true // attribute not defined in `define`
```
when I do `map.serialize()` `someAttr` gets in the result too (in minor). I thought it is not correct behaviour?

**Comment by whitecolor** [comment]
@imjoshdean 
https://github.com/bitovi/canjs/pull/1425

**Comment by justinbmeyer** [comment]
I'm not sure what you mean.  Do you mean:

```
var MyMap = can.Map.extend({
  define:{
   '*': {serialize: false}
  },
  someAttr: true
})

new MyMap().serialize().someAttr //-> true
```

?

If so, yes this is a bug.

**Comment by whitecolor** [comment]
Probably I'm wrong! Don't know why it didn't work for me.
