### ISSUE TITLE
Ability to Interrupt a Route Change

### ISSUE THREAD

**Issue by joe-crick** [bitovi/canjs#1830]
Need to add the ability to interrupt a route change, for circumstances such as warning a user about unsaved changes on a page when they attempt to navigate away from that page. This could be abstracted to be the ability to interrupt a change to a can.Map, or a specific property on a can.Map. An example of the desired behavior is detailed in the attached Activity Diagram:
![unsavedchanges](https://cloud.githubusercontent.com/assets/5924684/9092730/b5ff1606-3b5c-11e5-98ff-d694535eaf9f.png)

**Comment by justinbmeyer** [comment]
Breaking this down a bit:

### User initiates a change to the application route to go to another page

If they _click a link_, we are intercepting it, so we have the ability to prevent the URL from changing, although it might be difficult to wire up correctly.

If they _click the back button_, I don't think there's a way to prevent the url changing.  But, we should investigate.  Perhaps a beforeonunload event is fired, but I doubt it.  If there isn't a way to prevent the url from changing, we need to prevent appstate from committing the change, and if the change is prevented, rolling back the url (a replace state) without causing any other `can.route` property changes.

### Before changing the route DATA the application checks to see if a model is dirty.

I propose a "changing" event that could be paused, resumed and canceled like:

```js
can.route.bind("changing", function(ev){
  if( model.isDirty() ) {
    ev.pause();
   $.modal("do you want to stay on the page", {
     yes: function(){
       ev.cancel();
     },
     no: function(){
       ev.resume();
     }
   })
  }
});
```

For this to work, an async form of dispatch will be needed.  I think something like including a 4th argument will make it async:

```
can.dispatch.call(target, event, [ args ] , defaultBehavior)
```

can.Map would use it internally like:

```js
can.dispatch.call(this, "changing", [ attr, how, newVal, oldVal], function(){
   // code that actually sets the value here
})
```

I believe you'd have to overwrite `can.Map.__set` and `can.dispatch` in a plugin.

**Comment by justinbmeyer** [comment]
```js
can.dispatch.call(target, event, [ args ] , defaultBehavior, cancelBehavior)
```

```js
if(this.__bindEvents.changing) {


  can.dispatch.call(this, "changing", [ attr, how, newVal, oldVal], function(){
     // code that actually sets the value here
  }, function(){
     can.dispatch(this, "change-prevented", [ ]);
  })
} else {
  // do normal stuff
}
```

```js
can.route.data.bind("change-prevented", function(){
  // set url back to what it was
})
```

**Comment by daffl** [comment]
This is now in a separate module at https://github.com/canjs/can-interrupt
