### ISSUE TITLE
fix slides and move video and slides into @body

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1837]
http://canjs.com/docs/can.route.html says:

> In the following CanJS community we also talk about web application routing:

Followed by an empty space.

Also, content is in the @description when it should be in the @body.

The @description should never have more than a sentence or two giving a high-level overview of the technology.

**Comment by James0x57** [comment]
This is all cleaned up and taken care of (and live):
http://canjs.com/docs/can.route.html
Talked with Ilya briefly to confirm he didn't intend to do anything else for this one.
Good to go, closing! (Thanks Ilya!)
