### ISSUE TITLE
Minor: 2nd argument to stache system renderer is assumed to be a scope object, but it might not be.

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/canjs#1843]
https://github.com/bitovi/canjs/commit/1d7be0a30e4893f660fab3ab071dc7411c18cd93#commitcomment-12607871

See what https://github.com/bitovi/canjs/blob/master/view/stache/html_section.js#L68 does.

**Comment by matthewp** [comment]
This is fixed in minor.
