### ISSUE TITLE
Model create, update, delete state in template, like List promise

### ISSUE THREAD

**Issue by pilou** [bitovi/canjs#1847]
Usually when I save a model, its right after submitting a form, and I have to visually tell the user that the saving is in progress. For example a loading animation with a layer on the form, so the user can see it.

I do it like this, 4 example in a component (not a working code, but you will get the point):

    a-component.js
    Component.extend({
      ...
      viewModel: {
        saving: can.compute(false)
      },
      events: {
        'form submit': function ()  {
              this.viewModel.saving(true)
              this.viewModel.model.save(function () {
                    this.viewModel.saving(false);
              })
         }
      }
    })

In template the change of the `saving` compute changes the view between the ajax in progress, and the normal mode. Like this minimal thing:

    a-template.mustache
    {{#if saving}}
       saving
    {{else}}
      <input type="submit">
    {{/if}}

I do like the list promise plugin with the isPending, isResolved, isRejected states.

It would be nice to have something like this rather than the example above:

    a-component.js
    Component.extend({
       ...
    })

    a-template.mustache
    {{#if model.isCreating}} // or isUpdating; isDeleting
       saving
    {{else}}
      <input type="submit">
    {{/if}}

**Comment by justinbmeyer** [comment]
I just added this to can-connect. You can use it along-side can.Model.  Would you consider using that?

**Comment by pilou** [comment]
Well yes and no :)

Sorry for my bad english...

I would say yes because the feature is written there, and I am willing to use any good code made by the open source community. But,

I say no because, can-connect seems like (dont be mad at me, I had just a couple of minutes on the github site, and at the downloaded source):
- the build is failing - and I need this for production in two weeks
- not well documented, if I learn it from reading the codes I have to teach my colleagues, rather sending just a link to the doc page
- looks like Its not adding fetures to can.Model, but creates another implementation, that sould be learned, and not all the features in can.js are in can-connect. Also I cant see how to implement on top of can.js. But maybe its only in my head because I cant see the big picture without proper documentation.
- I would like better a plugin implementation with less dependency

Im sorry if my statements are incorrect, but I'm not familiar yet with can-connect, and it seems like I wont without a documentation like can.js has.

**Comment by justinbmeyer** [comment]
Travis started having problems with CanJS, that is why the build is failing. All of its tests pass.  I use have to update Travis, which I'll do later today. 


can-connect is arguably better documented:

http://connect.canjs.com/doc/index.html 

Where can.Model has all its features merged into one construct, can-connect has many simple behaviors, each documented. It makes documenting can-connect much easier. 

can-connect has many more features then can.Model. I'm not sure what gave you the perception that it does not. What did?

I'm not sure what you mean by a better plugin implementation with less dependency, but that sounds like exactly what can-connect is. With the exception of its CanJS specific parts, it doesn't depend on CanJS or even jQuery.

**Comment by pilou** [comment]
Maybe the biggest problem, is that on the github page (https://github.com/canjs/can-connect), there is no link to the documentation site.
The downloaded, and extracted github zip has an error: `index.html` redirecting to `/doc/`, to a non-existing dir.

Now I can see `http://connect.canjs.com/doc/can-connect|can|model.html` so I'm (starting to) understand what does it do, you can imagine reading this page https://github.com/canjs/can-connect with the lack of knowledge.
The less features perception was beacuse of that. Because I couldnt navigate to the "subdocumentation" like the `/can-connect|can|model.html` page.

I see that in can.js 3.0 the can.Model will be deprecated (seeing it here http://connect.canjs.com/doc/can-connect|can|model.html), and I feel really bad about that, because we started implementing an application migrating from JMVC with ejs, 3-4 weeks ago. On the can.js http://canjs.com/docs/can.Model.html page there was no sign of deprecation, so our brand new code will be deprecated, and we didnt know about that.

Do I guess right that can.js will deprecate the Model, and let can-connect handle it, so can-connect will do the CRUD commications with the server and everything connected with that feature, and can.js will be an application framework without saving any data?

I could not find the behavior that I mentioned in my original question, could you point me to it?
Or its not imlemented but can be done with `connect.behavior("my-behavior ..."`

**Comment by justinbmeyer** [comment]
Why couldn't you navigate to the subdocumentation?

can-connect has a "mostly" backwards compatible `can.Model` so if you've started using `can.Model`, your code won't have to change.  Furthermore, the [can/map](http://connect.canjs.com/doc/can-connect%7Ccan%7Cmap.html) behavior produces Maps that looks almost identical to can.Models.  Also, that is the extension that adds the [isSaving](http://connect.canjs.com/doc/can.Map.prototype.isSaving.html) method.

Please read this section about migrating can.Model's to can-connect:

http://connect.canjs.com/doc/can-connect%7Ccan%7Cmodel.html#section_Upgradingcan_Modelstocan_connect

Hopefully you'll see it's pretty straightforward.

I'm about to add a .findAll / .findOne alias to .getList / .get so upgrading should be even easier.

**Comment by pilou** [comment]
I could go to subdocumentation because I wasnt aware of the http://connect.canjs.com/ its **not mentioned anywhere** (not even on the github page https://github.com/canjs/can-connect) :)
So I could only see only the github page, what is basically the can-connect index page (http://connect.canjs.com/doc/index.html) without proper formatting.

I've seen the migration guide, and yes ist pretty straight forward.
The migration wont be a problem.
My problem is the **lack of info on can.js that can.Model will be deprecated** and I should use can-connect instead.
So my work hours migrating could go directly to implementing can-connect instead and getting more familiar to it.

Can you verify that can.Model will be deprecated and can-connect will be the "official" server saving thingy for can.js?

The `isSaving` function is perfectly good for me. More than good. I will save a lots of lines of code in my controls/components :)
You should consider also imlplementing a isCreating, and a isUpdating function so if sbdy needs exactly know "how" its being saved.
So in a Todo app you could write 'Creating todo', or 'Updating todo' instead the boring :) 'Saving...' with small effort.

**Comment by justinbmeyer** [comment]
I added the link to the docs in github after you first pointed it out.  It's there now.

> My problem is the lack of info on can.js that can.Model will be deprecated and I should use can-connect instead.

Typically, we don't deprecate something until we have the fully fleshed out alternative totally ready.  I'm currently in the process of officially releasing can-connect.  Until then, I'm not going to put the deprecation notice.  I was planning on getting it done last week, but won't be able to resume it until after next week.  

Also, the `can.Model` produced by `can-connect` passes almost all of `can.Model`s tests.  So there will be a version of `can.Model` for many, many years, to come.

I'm just suggesting you try `can-connect` now because it solves your problem and will get you "ahead" of things.  The `super-model` is really useful: http://connect.canjs.com/doc/can-connect%7Ccan%7Csuper-map.html.  We've started to use it in production apps internally.  

> Can you verify that can.Model will be deprecated and can-connect will be the "official" server saving thingy for can.js?

Yes, I can verify this.  The goal of `can-connect` is to be a much better replacement for `can.Model` while still:

- providing a high-fidelity backwards-compatible version.
- providing `can/map` which makes a map instance that looks and works very similar to a `model` instance.

> You should consider also implementing a isCreating, and a isUpdating function so if sbdy needs exactly know "how" its being saved.

I was thinking about that, but you can simply combine `isNew` with `isSaving` like:

```
{{#if thing.isSaving}}
  {{#if thing.isNew}}Creating{{else}}Updating{{/if}}
{{/if}}
```

That being said, create an issue in `can-connect` and I'll add them.

**Comment by justinbmeyer** [comment]
Also, some other uses of can-connect:

https://github.com/donejs/bitballs/tree/master/public/models

**Comment by pilou** [comment]
Combining `isNew` and `isSaving`, is good enough. I think there is no need for the shortHand functions.
The example you written should be on http://connect.canjs.com/doc/can.Map.prototype.isSaving.html page.

I will release our app with can.Model extending, but after the release I will start experimenting with can-connect, replace our Models with `can-connect/can/model` or `can-connect/can/super-map` I dont know yet.
