### ISSUE TITLE
A define property's getter will reach maximum call stack size if...

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1850]
...the define property is a list and the getter reads it's own length and the length of that list changes:

```
define: {
  list: {
    get: function () {
      var list = this.attr('list') || new can.List(); // Safe
      var length = list.attr('length'); // Un-safe (Maximum call stack size exceeded.)
      if (...) {
        list.push(...)
      }
      return list;
    }
  }
}
```

I expected this not to work when I called `this.attr('list')`, but when it did I continued on until I found that `this.attr('list').attr('length')` caused the loop. 

I got around the issue in my case by wrapping the call to `list.attr('length')` in a `can.__notObserve()`, but I'm curious if this was meant to work as `this.attr('list')` did. 

Actually, I suppose the `this.attr('list')` binding wouldn't cause a loop because "list" was never re-set. So now I'm thinking it'd be pretty cool if we could detect and prevent the binding that caused the loop when a getter attempts to read itself. 

/cc @justinbmeyer

**Comment by justinbmeyer** [comment]
Are you using latest?  I thought this was fixed.

https://github.com/bitovi/canjs/blob/master/compute/get_value_and_bind.js#L33

and

https://github.com/bitovi/canjs/blob/master/compute/proto_compute.js#L49

should prevent a compute from calling itself while it is being observed.

**Comment by akagomez** [comment]
I am not. I'm sure that's the issue. Thanks for the clarification.
