### ISSUE TITLE
Update pre-release version package as pre-release on NPM

### ISSUE THREAD

**Issue by cklanac** [bitovi/canjs#1856]
The can package shows the pre-release as the latest on NPM

**Comment by matthewp** [comment]
How do you do this?

**Comment by mjstahl** [comment]
Based on https://docs.npmjs.com/misc/semver#prerelease-tags we would do something like `2.3.0-alpha.11`

Though it seems like we are doing it correctly.  Based on the comments at: 

https://github.com/npm/node-semver/blob/master/semver.js#L62
https://github.com/npm/node-semver/blob/master/semver.js#L75 

our releases should be considered pre-release.

**Comment by daffl** [comment]
I think it's a command line flag for `npm publish`

**Comment by daffl** [comment]
We will make sure that we do official pre-releases in the next minor/major version.
