### ISSUE TITLE
can.bind should support objects with on and addEventListener methods

### ISSUE THREAD

**Issue by mjstahl** [bitovi/canjs#1862]
This is so that objects that support the EventTarget interface, and objects following the newer jquery convention of `on` can be used in templated event handlers in a can.Control, and more importantly, a can.Component.

We check for the `bind` function here:
https://github.com/bitovi/canjs/blob/master/util/jquery/jquery.js#L53

**Comment by mjstahl** [comment]
`isBindableElement` should support anything that has `addEventListener`

https://github.com/bitovi/canjs/blob/master/util/jquery/jquery.js#L2

**Comment by justinbmeyer** [comment]
@mjstahl @daffl is this "closed in a branch"?

**Comment by mjstahl** [comment]
@justinbmeyer I need to come back to this... for some reason, no matter what I do I can't get the tests to run on the CI.  They all run in the browser and on the command line just fine, but not in the CI.
