### ISSUE TITLE
Resurrect ^ syntax

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1864]
I don't remember why this was disabled but if the reason is a lack of use case I have one. If you're using can-connect/can/tag there is no way to access the tag's value (the model instance) in your viewModel.  Consider:

```handlebars
<todos-model get-list="{status='complete'}" ^todos="{value}">
  {{#isResolved}}
  <li class="todos">...</li>
  {{/isResolved}}
</todos-model>
```

I don't know if a better way to get the `todos` list than the `^todos` syntax. This seems like the most elegant way as well.

**Comment by matthewp** [comment]
Opinions @justinbmeyer ?

**Comment by justinbmeyer** [comment]
Well, I'm not a fan of this use case.  If you want the todos in your view model, you should probably add:

```js
define: {
  todos: {
    value: Todo.getList.bind(Todo, {status: "complete"})
  }
}
```

**Comment by justinbmeyer** [comment]
@matthewp can we close this?

**Comment by matthewp** [comment]
I'd still like this behavior, but a separate project might be the way to go. In a refactoring scenario I think it's asking too much to completely change your template (and not use can.connect/tag) and refactor into the viewModel when a simple attribute could give you what you need. I understand that you probably wouldn't write it that way if you needed the todos in your viewModel from the start.

Let me relook at the code and make sure it's not using any undocumented apis and I'll create a separate repo for this.

**Comment by justinbmeyer** [comment]
Closing for now ...
