### ISSUE TITLE
Stache bug with #reference exports

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/canjs#1865]
If a stache condition wraps a component that is exporting its entire view model 2-way like in the below example, if the condition starts out false and becomes true, an error is produced.

```html
{{#eq page 'bar'}}
  <test-component #test-vm></test-component>
{{/eq}}
```

It seems the refs scope sees a change to `testVm` and throws an error while trying to run the compute to update the child. I don't think the change should be perceived in the first place.

http://jsbin.com/huhekilusu/1/edit?html,js,console,output

For anyone experiencing this issue, my current workaround is to use a 1-way binding which seems to be sufficient for all my use cases.

```html
<test-component #test-vm="{{.}}"></test-component>
```

**Comment by justinbmeyer** [comment]
So is the real problem here #1866 ?

**Comment by dylanrtt** [comment]
I'm not sure how related it is. I did manage to reproduce it with just a `can.Map` like the other issue so it's also not related to the router.

http://jsbin.com/tapileheda/edit?html,js,console,output

The difference here is that only one property is changing.

**Comment by dylanrtt** [comment]
This appears to now be fixed in minor as a result of the bindings rewrite.
