### ISSUE TITLE
Conditional "readonly" attribute does not work

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/canjs#1874]
I can use a mustache condition block to make an element have a conditional `disabled` attribute but it does not work with `readonly`. It simply never applies the attribute regardless of the condition's truthiness.

http://jsbin.com/horehelute/edit?html,js,console,output

**Comment by justinbmeyer** [comment]
Interesting.  I assumed it work would b/c `readonly` is configured here: https://github.com/bitovi/canjs/blob/minor/util/attr/attr.js#L47

**Comment by justinbmeyer** [comment]
@alexisabril this is probably pretty simple.  Although the test should probably take place in can/util/attr.  I would start there to make sure it's doing what it should be doing.

**Comment by DesignByOnyx** [comment]
`readonly` attribute maps to `readOnly` property - could be a start...

**Comment by daffl** [comment]
Closed via #1920
