### ISSUE TITLE
Missing Doc can.Deferred.prototype

### ISSUE THREAD

**Issue by pYr0x** [bitovi/canjs#1890]
it seems that no one took a note of that issue, so i will repost it here.
https://github.com/bitovi/canjs.com/issues/254

> The documentation about deferred is lost.
> http://canjs.com/2.0/docs/can.Deferred.prototype.html

**Comment by nlundquist** [comment]
I think I see what you mean. In later versions of the docs that page doesn't exist and there is no way to navigate to the documentation of the members of the prototype like then, always, etc. even though the docs are generated for them, like http://canjs.com/2.3-pre/docs/can.Deferred.prototype.always.html. I'll be investigating this.
