### ISSUE TITLE
Component helper is not working in child component

### ISSUE THREAD

**Issue by pYr0x** [bitovi/canjs#1908]
bad issue?!
http://jsbin.com/numacijado/edit?html,js,output

## Edit
i figured out, that 
```template: '...my template...',```
uses mustache as default.

mixing mustache and stache templates causes this error

maybe stache should be the default template language for can.component?

**Comment by justinbmeyer** [comment]
@pYr0x It will be in 3.0. But we can't do that until then.  Perhaps we could make some type of configuration.  If you are interested in making that happen, let me know and I'll re-open the issue.
