### ISSUE TITLE
Rename ~ helper

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1932]
Because of #1699 we need to rename it. A few options:

```handlebars
{{root "img/foo.png"}}

{{base "img/foo.png"}}

{{join "img/foo.png"}}

{{join-root "img/foo.png"}}

{{join-base "img/foo.png"}}

{{base-url "img/foo.png"}}
```

**Comment by matthewp** [comment]
I like either `join` or `join-base` because that is what they do.  join-base is more accurate.

**Comment by Alfredo-Delgado** [comment]
Why not `{{baseUrl}}"img/foo.png"`?

**Comment by matthewp** [comment]
@Alfredo-Delgado So this would be a helper that simply returns the baseUrl as a string, doesn't do any joining, and use normal stache to do whatever you want?  Not a bad idea... going to think about that some more.

**Comment by matthewp** [comment]
Is the normal convention to kebab-case or camelCase helper names?

**Comment by justinbmeyer** [comment]
@Alfredo-Delgado That wouldn't work with `{{baseUrl}}../../path.png` sorta thing.  But a cool idea.  We could actually make `{{#join}}../../path.png{{/join}}` work.

@matthewp for now, I'm going to go with `joinBase`.  Most helpers are camelCase.  I'm going to make this change now b/c I need it for tests to pass.

**Comment by matthewp** [comment]
This is in minor.
