### ISSUE TITLE
Can-event gets broken in production if method does not exist.

### ISSUE THREAD

**Issue by ilyavf** [bitovi/canjs#1942]
```
<div can-click="nonExistingMethod"></div>
```

[This block] (https://github.com/bitovi/canjs/blob/master/view/bindings/bindings.js#L201) gets executed in development but is removed in production which causes an error in case a method does not exist.

In production because the line [206] (https://github.com/bitovi/canjs/blob/master/view/bindings/bindings.js#L206) is removed, execution goes further and line [259] (https://github.com/bitovi/canjs/blob/master/view/bindings/bindings.js#L259) `scopeData.value.apply` causes an exception because  `scopeData.value` is `undefined`.

**Comment by daffl** [comment]
This has been fixed via #1943
