### ISSUE TITLE
2.3.0-pre.11: can.Component's inner Control not tearing down events

### ISSUE THREAD

**Issue by marshallswain** [bitovi/canjs#1944]
It looks like event teardown for can.Component events object/can.Control is broken in the latest can.  Upgrading from 2.2.6 to 2.3.0-pre.11 we are now seeing issues with our project.

These events, which are part of the page-level component, do not get torn down when the element is removed:
'{viewModel.appstate} globalSearchReady': function(){}
'{window} resize':function(){}

So every time you visit the page, you get duplicate handlers.

@ilyavf made a JsBin demonstrating the problem: http://jsbin.com/fobake/edit?html,js,console,output
If you resize the page (e.g. with showing/hiding HTML section) you will see the event being called twice.

**Comment by ilyavf** [comment]
Fixed with [this PR] (https://github.com/bitovi/canjs/pull/1945)
