### ISSUE TITLE
Issue with rendering in can 2.3pre

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1950]
In last version 2.3pre12 (and in others) strange incorrect rendering:

```HTML
<div class="input-group">
  <input type="text" placeholder="Search" class="input-sm form-control"/>
  <span class="input-group-btn">
    <button class="btn btn-default" type="button">Go!</button>
  </span>
</div>
```
is rendered like:
![image](https://cloud.githubusercontent.com/assets/736697/10044323/5a328528-6213-11e5-9921-3b96e438ac26.png)

![image](https://cloud.githubusercontent.com/assets/736697/10044321/549e35c6-6213-11e5-9e28-3683be814db2.png)

**Comment by matthewp** [comment]
@whitecolor Thanks, I think this is the same as #1189, no?

**Comment by whitecolor** [comment]
@matthewp yes it is the same) coun't find it.

**Comment by whitecolor** [comment]
It seem the fix for now is to replace `<span>` with `<a>` that allows block elements inside.

**Comment by alexisabril** [comment]
Closing as a duplicate(this issue is referenced in #1189)
