### ISSUE TITLE
Event binding syntax: functions applied with the wrong context

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1970]
Consider a template like:

```handlebars
<form ($submit)="doSearch()">...</form>
```

Where doSearch is a function on the component's viewModel.  The value of `this` in doSearch should be the component's viewModel instance. Instead it is `window`.  The problem is here: https://github.com/bitovi/canjs/blob/minor/view/bindings/bindings.js#L257

There is no scopeData.parent property, it's undefined.  I believe this should be `scopeData.scope._context`.

Will submit a breaking test in the morning.

**Comment by justinbmeyer** [comment]
I've fixed this in my branch.  There's a few context bugs that I've found.  I'll push what I have tomorrow.

**Comment by justinbmeyer** [comment]
I think this is fixed.
