### ISSUE TITLE
Is there a way to assign the whole viewModel of a component on instantiation?

### ISSUE THREAD

**Issue by scaryzet** [bitovi/canjs#1978]
I'm making a list-like component in my application and I would like to extract the list item into a separate child component. I've struggled for a while but found no way to assign viewModel of a component on instantiation.

Stripped example:

    can.Component.extend({
        template: '{{#items}}' +
                  // '<item data="{.}"></item>' + // (1) Can do this.
                  // '<item title="title" value="value"></item>' + // (2) Can do this
                  '<item @viewModel="{.}"></item>' + // Want something like this.
                  '{{/items}}'
        // ...
    });
    
    can.Component.extend({
        tag: 'item'
        // ...
    });

Working example on jsfiddle: http://jsfiddle.net/scaryzet/7pnh5ujn/1/

Currently I know of 3 ways to cope with this.

1. Bind child component's data to a key (like in my fiddle by the link above).
2. Bind all needed fields by specifying them all in the tag - pain in ass.
3. Don't extract individual list items to separate components.

I hope there is a solution to my problem.

**Comment by justinbmeyer** [comment]
For #1, I would avoid using @viewModel as your key.  I'd just call it "item" or something.  `@` is reserved.

But the easy solution is probably to use a viewModel function;

```js
can.Component.extend({
  tag: "item",
  viewModel: function(attrs, parentScope){
    return parentScope.context
  }
})
```

viewModel functions let you specify any crazy stuff you want.

**Comment by scaryzet** [comment]
Thank you. I'll try that. My mistake I didn't read about viewModel in the docs: http://canjs.com/docs/can.Component.prototype.viewModel.html Pretty powerful, I like that.
