### ISSUE TITLE
`if` helper argument is undefined in 2.3

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#1983]
Template case: `{{#book}}{{#if isOpend}}...{{/if}}{{/book}}`

`isOpened` is a function on the scope.
```javascript
scope: {
  isOpend(book){
     return this.attr('openedId') == book.id
  }
}
```
In 2.2. `isOpened` has `book` (current context) as first agrument and in 2.3 `isOpened` has no arguments passed, is it by design?

**Comment by matthewp** [comment]
Not intentional, it's a bug.

**Comment by whitecolor** [comment]
Is it going to be fixed soon?

**Comment by matthewp** [comment]
Can you submit a test?

**Comment by whitecolor** [comment]
Seem to work now
