### ISSUE TITLE
Returning 0 from a helper displays nothing

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/canjs#1985]
Not sure if this has been reported already, but I think returning the number 0 from a helper should display the 0. It currently displays nothing. I'm guessing there is a truthy check on the helper's output.

```
// when bar is 0
{{ bar }} // prints "0"
{{ myHelper bar }} // blank (myHelper simply returns the value())
```

http://jsbin.com/helasubejo/edit?html,js,output

**Comment by DesignByOnyx** [comment]
There is a truthy check here: https://github.com/bitovi/canjs/blob/master/view/stache/mustache_core.js#L535

We need to make sure this wouldn't be a breaking change as some authors might return 0 with the intent of *give me an empty string*.

**Comment by justinbmeyer** [comment]
This is a bug.  Returning 0 to get an empty string wouldn't make sense and its not documented that way so it's ok to change prior to 3.0.

**Comment by asavoy** [comment]
This would be the stache equivalent to this mustache issue: https://github.com/bitovi/canjs/issues/1109
