### ISSUE TITLE
New bindings do not always update the scope

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/canjs#1996]
Version: `v2.3.0-beta.6`

http://jsbin.com/gakibebibu/edit?html,js,console,output

Using `can-value="foo"` or `{($value)}="foo"` on a text input, if I blank out the text box to an empty string, the scope is not updated. Instead, the old value remains. In some cases in my app, it would immediately update the element with the old value but I couldn't easily reproduce that here.

**Comment by justinbmeyer** [comment]
good find. I'll fix this right now.
