### ISSUE TITLE
Language selection guides

### ISSUE THREAD

**Issue by whdigger** [bitovi/canjs#1998]
I can help do it translate into Russian language. Would it be possible to put on the site for language selection guides?

**Comment by justinbmeyer** [comment]
@whdigger Thanks for offering to help.  We are going to release a new guide with 2.3.  At that point, getting a russian translation would be great.  Thanks!

**Comment by whdigger** [comment]
For translate I need to fork the project, checkout v2.3.0-pre.13, and translate folder guides, and later send pull request
Tell me how to generate the html page via documentjs `./node_modules/.bin/documentjs`  which must be the generation of project files?

**Comment by whitecolor** [comment]
@whdigger *facepalm* learn english http://babeleo.com
kiddin`

**Comment by whdigger** [comment]
@whitecolor I feel you want to help me?

**Comment by whitecolor** [comment]
@whdigger ping me on skype alex.oshchepkov
