### ISSUE TITLE
Stache #each teardown throws an error on observable functions

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/canjs#2001]
I don't know if this was an intentional feature, but you used to be able to do `#each` on a viewmodel's observable prototype function. For example:

```js
// viewmodel
var VM = can.Map.extend({
  myList: function() {
    return this.attr('myOtherList');
  }
});

// stache
{{#each myList}} ...
```

http://jsbin.com/leladosese/edit?html,js,console,output

You still can, but the teardown throws an error on [live.js#L442](https://github.com/bitovi/canjs/blob/09261099525648b14997b08e657a8994baa498fc/view/live/live.js#L442) because the function (not a compute) doesn't have an `unbind` method. This error did not occur in `pre.8` and is now showing up since I updated to `beta.6`.

Strangely, it works fine if there is no element wrapping the `#each` in that example.

I don't personally care about this feature because I was able to just move it to a virtual property where it I think it belongs, but now you know in case you want to continue to support it.

**Comment by justinbmeyer** [comment]
Looks like a bug.  I'll take a look in 20 min.  Thanks!

**Comment by justinbmeyer** [comment]
So, it seems like the problem is calling .empty() right?  This issue makes it sound like you can't do `#each`.  You can do `#each`, just the tearing down isn't working right?

**Comment by dylanrtt** [comment]
Yes, that's correct. Sorry for not clarifying.

**Comment by justinbmeyer** [comment]
So there is something I would like to get rid of, but can't until 3.0.  

Basically, the current behavior is to call functions if they are on a `can.Map`, but not to call functions if they are not.  

Fortunately, `call expressions` clean this up by always calling functions.  

In 3.0, we will probably clean this up, or make `helper expressions` adopt `call expression` behavior entirely.

For now, I'm going to add a special flag to `can.compute.read` that `HelperScopeLookup expressions` will use to say "give me the function, unless it's on a can.Map. If it is on a can.Map, call the function and give a compute".
