### ISSUE TITLE
Teach can.Component.extend respect can.Component.defaults

### ISSUE THREAD

**Issue by scaryzet** [bitovi/canjs#2005]
Feature request: Teach can.Component.extend respect can.Component.defaults, or something like that.

It would allow to set `leakScope` to false globally. Currently it seems you can't do that. And you can't extend Components from Components. A custom "component-creator" function which merges options would do but that's ugly.

**Comment by justinbmeyer** [comment]
I think making extending components work is the ultimate goal here.  

In the short-term, I'm pretty sure you can already do this with:

```
can.Component.prototype.leakScope = false;
```

closing.  reopen if that doesn't work.
