### ISSUE TITLE
Create new Model or delete causes JSON parse error

### ISSUE THREAD

**Issue by dhs3000** [bitovi/canjs#2010]
My REST service returns 210 Created with the new URL when a new model is posted to the service. The can.js Model expects a JSON datatype. 

Same for DELETE, my REST service returns just 200 OK, can.js expects me to return JSON.

If this is not an intended behavior, maybe "ajaxMaker" in Model should call "ajax" with an expected datatype for the "ajaxMethod".

**Comment by justinbmeyer** [comment]
@dhs3000 Thanks, but I'm not sure what error you are reporting exactly.  Are you saying if someone does something like:


```js
new MyModel({foo: 'bar'}).save()
```

And the server returns JSON like: `{"id": 5}`, can.Model is breaking?  I think that's unlikely.  We do that all the time w/o any problems.  We do it so often, that I suspect you mean something different. 

Thanks again!

**Comment by justinbmeyer** [comment]
I originally misread what this issue was saying.

Yes, it's expected that a model like:

```
can.Model.extend({
  create: "POST /things"
},{})
```

MUST return JSON.  I do think setting the `dataType` property makes sense.

**Comment by justinbmeyer** [comment]
It seems like it's already set to default to 'json':

https://github.com/bitovi/canjs/blob/master/model/model.js#L85

https://github.com/canjs/can-connect/blob/master/src/data/url/url.js#L231

If this is the case, the parse error should be given.

**Comment by dhs3000** [comment]
Yes, the default datatype seems to be "JSON". 

As far as I understand neither DELETE nor POST are expected (by REST standards) to return any data. (Post might return an Location header to the newly created resource.)

If I have a Model with
> can.Model.extend({
  destroy: "DELETE /things/{id}"
},{})

in the moment the REST service must return a dummy JSON as otherwise it causes a parse error.

**Comment by justinbmeyer** [comment]
> As far as I understand neither DELETE nor POST are expected (by REST standards) to return any data. (Post might return an Location header to the newly created resource.)

That's correct.  There's two reasons for this:

1. When JMVC/CanJS was being originally designed, getting some servers to do everything REST-fully was not easy.  Not nearly as easy as returning some JSON data to signal the ID.  

2. There's occasions where the `location` header is not enough.  For example, sometimes there's additional information that gets added to a type when it is created.  For example, `updateAt` and `createdAt` properties.  We don't want to have to make an additional AJAX request to fetch these properties.  

I agree that it would be nice to support these, the most restful, of restful services.

For `DELETE` we can probably handle any successful response.

For `POST` it's a bit tricker.  We need the ID.  When I've been on services that return the location header, I've had to parse it out.  This is easy to do with your own custom "create" hook.  Something like the following (though I'm sure there a bugs):

```
{
  create: function(data){
    return $.post("/things", data).then(function(response, jqXHR){
      return {id: jqXHR.getResponseHeader("location").match(/things\/(\d+)/)[1]}
    });
  }
}
```  

But to make this work, we'd probably have to use the `findOne` template to sniff out the ID value.


Then there's the problem of making this work without 'json' as the default `dataType` value and still be backwards compatible.  It might be possible if we take-over response processing from jQuery.  

Making this change in can-connect would be the place to start.  If you are interested, I can show you where to start.  Making it in can-connect is actually much easier.

**Comment by dhs3000** [comment]
Thank you for response. 

I understand the `POST` expecting JSON, it makes sense now :) It might be too much _magic_ trying to _guess_ the `id` and the second request to load the data is not efficient. I didn't think so far.

But, I couldn't find it in the documentation - maybe I was looking at the wrong one, I looked at the main Model documentation page. [Here](http://canjs.com/docs/can.Model.create.html#sig_can_Model_create___METHOD__path_to_resource_) it talks in the `Returns {can.Deferred}` part about `Object with ID property`.

----

For `DELETE` it seems to me reasonable to accept any success status code without looking at the response.

I tried setting the `dataType` for `DELETE` to `text` and it worked. But I just started looking at the framework so I don't know if that would be the _right_ place and way to do it.

**Comment by justinbmeyer** [comment]
@dhs3000 if you are just starting, I'd take a look at http://connect.canjs.com/.  It's not officially released yet, but it will be what we start migrating people to very shortly.  

It's very similar to `can.Model`, and even has a [backwards compatible api](http://connect.canjs.com/doc/can-connect%7Ccan%7Cmodel.html), but it's far more powerful, and uses mixins instead of inheritance.   

By powerful, I mean you can easily add things like fall through caching, real time behavior, caching all requests, and more.

By using mixins, I mean that you could create your own versions of [data-url](http://connect.canjs.com/doc/can-connect%7Cdata-url.html) that works restfully nicely, share it with others, and they could easily mix it into their connections.

This is in contrast to can.Model where you can really only inherit from base Models.  But you can't mixin multiple behaviors easily.

[DoneJS](http://donejs.com/) (also not released yet) uses can-connect too.

**Comment by dhs3000** [comment]
Thanks, I will look take a look at, sounds interesting.
