### ISSUE TITLE
References of 'can' not locally scoped in modules

### ISSUE THREAD

**Issue by Psykoral** [bitovi/canjs#2022]
<pre>>> Error: define: Can't find variable: can </pre>

Observed in https://github.com/bitovi/canjs/releases/tag/v2.3.0 by PhantomJS running a build with:
<pre>window.GLOBALCAN = false;</pre>

Confirmed that setting window.GLOBALCAN = true / not setting window.GLOBALCAN resolves the issue.

The issue is found in these files:
* https://github.com/bitovi/canjs/blob/master/map/map_helpers.js#L6
* https://github.com/bitovi/canjs/blob/master/list/sort/sort.js#L1
* https://github.com/bitovi/canjs/blob/master/util/object/isplain/isplain.js#L1
* https://github.com/bitovi/canjs/blob/master/list/promise/promise.js#L1

'can.Something' is refereed within the body of the script but not as a module in function (can)

Should be resolved with https://github.com/bitovi/canjs/pull/2021

This is also in relation to a past issue of similar case:
https://github.com/bitovi/canjs/issues/673

**Comment by daffl** [comment]
Closed via #2021.
