### ISSUE TITLE
global var "GLOBALCAN" fails

### ISSUE THREAD

**Issue by espretto** [bitovi/canjs#2039]
i'm using the amd variant and was thus looking for a way to avoid canjs' global export. apparently "GLOBALCAN" needs be set to `false` in tandem with uglify's `dead_code` option. it works! but not for `can/amd/can/view/stache/utils.js` which is missing `can` in its argument list.

i would have annotated the exact code line on github but i couldn't find the amd-build. i guess you're generating that with stealjs so i opened an issue.

**Comment by daffl** [comment]
Just working on releasing a 2.3.1 which should fix this via #2021

**Comment by espretto** [comment]
great! could you do the same for `canjs/amd/can/view/mustache.js` > `window.Mustache`?

**Comment by daffl** [comment]
I wonder why `Mustache` gets added to the window. I'll add a condition to only do this when `GLOBALCAN` is true.

**Comment by espretto** [comment]
I'm currently upgrading from 2.1.1 to 2.3.1. the global `Mustache` still [leaks](https://github.com/canjs/canjs/blob/9382d592705c31e2da959d2eddf592dcaa410dd2/view/mustache/mustache.js#L120).
