### ISSUE TITLE
can.route triggers event two times for setting nested object.

### ISSUE THREAD

**Issue by schovi** [bitovi/canjs#269]
I want to use two level object in route for control some panel with widgets.
When i want to make widget visible i can easily trigger 
`can.route.attr({notifications: {messages: true}})`
and when i want to hide it i will call 
`can.route.removeAttr('notifications.messages')`
and each widget listen on route change for given 'code'
`can.route.bind('notifications.messages', function() {....})`
Idea worked fine until i find some strange behaviour that event is triggered 2 times.
First for whole object {notifications ...}
Second for notifications.messages (And there it pass new value as stringified `"true"` and old value as standard `true`

Thing with stringified true is even more stranger :)

More in console in this [Fiddle](http://jsfiddle.net/dD7Px/5/)

**Comment by justinbmeyer** [comment]
I think you can fix this with the define plugin:

```
var RouteState = can.Map.extend({
  define: {
    messages: {
       type: "boolean"
    }
  }
})

can.route.map(new RouteState);
can.route.ready()

can.route.bind("messages", function(){})

can.route.attr("messages", true);
can.route.attr("messages", false);
```

**Comment by daffl** [comment]
I would double check if this hasn't been fixed with #1187 yet which I merged yesterday.

**Comment by daffl** [comment]
Nervemind, that looks like it's something different.

**Comment by James0x57** [comment]
Looks to be fixed.
http://jsbin.com/remujuziho/edit?html,js,output
```
test( "deep param bind doesn't fire twice on remove", function () {
  expect( 1 );
  can.route.bind( "prop.deep", function () {
    ok( true, "only fired once because prop.deep changes" );
  });
  can.route.attr( { prop: { deep: true } } );
  // issue #269, remove would fire the change event for "prop.deep" AND "prop"
  can.route.removeAttr( "prop.deep" );
});
```
