### ISSUE TITLE
can.sub with strict properties mode

### ISSUE THREAD

**Issue by schovi** [bitovi/canjs#349]
Now when any of values is missing the `can.sub` returns `null`
I understand to needs of this in can.control and templated bindings.

I came with idea, how to improve `can.sub` as templating system.
And I call it `strict mode` and can be controlled with fourth param in can.sub function
```javascript
sub: function( str, data, remove, strict ) { ... }
```
When `true` is passed it returns `null` when any value is missing.
When `false` is passed it returns new template where missing values are kept as template (meta-template).

There is example of usage `strict` param:
```javascript
// Without strict
can.sub("a:{a} b:{b}", {b:"hello"}) // -> "a: b:hello"

// Strict to true (third param is for remove value)
can.sub("a:{a} b:{b}", {b:"hello"}, false, true) // -> null

// Strict to false
can.sub("a:{a} b:{b}", {b:"hello"}, false, false) // -> "a:{a} b:hello"
```

There is initial implementation https://github.com/schovi/canjs/compare/can-sub-strict

**Comment by justinbmeyer** [comment]
@schovi Thanks for submitting this issue.  However, I don't think it's something most people need, and its not something the framework needs.  can.sub is just a means to an end. Hopefully you can get this in lodash or some other micro-templating library.  Thanks!
