### ISSUE TITLE
Live binding does not maintain the cursor position.

### ISSUE THREAD

**Issue by vivoices** [bitovi/canjs#356]
This Fiddle:
http://jsfiddle.net/vivoices/CGPfA/
shows how LiveBinding receives text from an input element and then updates the element resulting in the cursor jumping to the end of the text.

Would it be possible to include an optional flag in the LiveBinding smart-tag, that, if set to true, prevents the template to update an element's value only in the case that the data change came from the same element?

**Comment by daffl** [comment]
Closed via #1452
