### ISSUE TITLE
can.route match order for absolute patch vs wildcards

### ISSUE THREAD

**Issue by schovi** [bitovi/canjs#497]
Have 2 simple controllers for matching routes.

```javascript
var PagesController = can.Control({
  ':id route' : function(data) {
    this.element.text("PagesController match")
  }
});

var WorkshopController = can.Control({
  'workshop route' : function(data) {
    this.element.text("WorkshopController match")
  }
});
```
now bind them
```javascript
new PagesController('body', {})
new WorkshopController('body', {})
```
and set route
```javascript
window.location.hash = "workshop"
```
result of text in body is `PagesController match`

I completely understand why is this happening. Router match first route which can be applied. It is like in almost every backend routers. But in these you can control order of them. Otherwise in dynamic page with javascript mostly you can't. Personally have no specific idea how to do this (maybe router can inside reorder routes based on absolute path and path with wildcard?).

playground http://jsbin.com/oCUSaYa/4/edit?html,js,console,output

**Comment by justinbmeyer** [comment]
We are going to remove this functionality in 3.0: #1435
