### ISSUE TITLE
Live binding of not-yet-defined attr in a Component's template fails

### ISSUE THREAD

**Issue by robertheessels** [bitovi/canjs#579]
A fiddle where using a not yet defined attribute in a template does not live bind correctly:

http://jsfiddle.net/robertheessels/VRE8Z/3/

When the undefined attribute is used inside a mustache template, the live binding is correct, but...
when the attribute is used inside the template of a COMPONENT, the live binding fails.

{{click}} works, {{notyetset}} does not work.
{{../click}} and {{../notyetset}} do work, and is probably the right way anyway, but then why does {{click}} work also?

At the very least this is inconsistent.

**Comment by justinbmeyer** [comment]
This is probably much more easy to accomplish now that I've pulled out the compute that reads from the scope into this module: https://github.com/bitovi/canjs/blob/master/view/scope/compute_data.js#L39 to fix #1617.

It should be possible now to detect if we've actually found the right root observable (because there is a value) and only then stop walking up the entire scope.

**Comment by gsmeets** [comment]
This is for me the most problematic behaviour when writing templates. Getting this fixed is important. I see it's been bumped a few times to future milestones. Can we get this fixed in 2.3? Do you need help with it?

**Comment by justinbmeyer** [comment]
@gsmeets Help would be great.  However, my hesitation has been around performance.  With a very nested structure, this could mean making 50 or so bindings.  

I suppose we could take the performance cost but let people know to either use:

- leakScope: false
- default their undefined values to null
- use ../

To get back any performance losses.

**Comment by justinbmeyer** [comment]
@gsmeets Added a pull request.  Please try this with your app and let me know if it works and performs ok.

**Comment by gsmeets** [comment]
I'll give it a go. I do run on 2.1.4 still though, so I'm hoping I don't have much patching to do.
