### ISSUE TITLE
Firefox errors when `can/map/attributes` plugin is included an attribute is named `watch`

### ISSUE THREAD

**Issue by retro** [bitovi/canjs#632]
Firefox will fails with the cryptic `TypeError: can't convert undefined to object` error if `can/map/attributes` is included and attribute name is `watch`

To reproduce it include `can/map/attributes` and do:

    var map = new can.Map({watch : 'foo'})

The reason for this is custom Gecko function on the object - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch

**Comment by justinbmeyer** [comment]
Check if this also breaks with the define plugin and latest FF.

**Comment by justinbmeyer** [comment]
Closing for #1437.
