### ISSUE TITLE
can.route.ignore

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/canjs#655]
```javascript
can.route.ignore("files/");
```
...would indeed be a mere interface for:
```javascript
can.route("files/", false);
```
…but, it'd self-document itself in our projects and would be an easy find in the official documentation.

**Comment by justinbmeyer** [comment]
@stevenvachon Any interest in making this happen?

**Comment by stevenvachon** [comment]
Not at this time.

**Comment by daffl** [comment]
I'm going to close this since it has been inactive for a while and nobody else was looking for similar functionality.
