### ISSUE TITLE
can.each nodeList support

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/canjs#678]
When looping through node list collections (jQuery in particular), it'd be great if we could loop through them without having to check if the `index` is [similar to] an integer.

*Instead* of having to do:
```javascript
can.each( can.$("a"), function(value, index)
{
	// Avoid length, and other non-array-like indexes
	if ( isNaN(parseInt(index)) ) return;
	
	can.append( can.$(value), "content" );
});
```
…we would have the proposed following:
```javascript
can.each( can.$("a"), function(value, index)
{
	can.append( can.$(value), "content" );
});
```

**Comment by cklanac** [comment]
Fix as of version 2.1.0. Added is isArrayLike() check.
