### ISSUE TITLE
Dev Warning : mutable values in can.Control.defaults

### ISSUE THREAD

**Issue by shcarrico** [bitovi/canjs#704]
This issue arises when mutable values are assigned via `can.Control.defaults`.

There are cases where people desire to use "defaults" as documentation for the options that are passed to their Control. It is a nasty bug cause when one assigns say, `can.compute()` as a default, then inits 3 copies of a control and has that compute being  inadvertently shared. 

I would also propose we explicitly call this out in the documentation for can.Control.defaults. If there is agreement, I will update the docs and open a merge for both of these.

**Comment by shcarrico** [comment]
I just experienced two individuals separately making this same mistake.. Would it be appropriate to submit a pull to improve the documentation to call this out more loudly in the documentation places around "static properties" ? The dev warnings are so loud that we have suppressed them...

**Comment by justinbmeyer** [comment]
Sure, sounds good.

**Comment by justinbmeyer** [comment]
@shcarrico If you can get that to us this week, we can put it in 2.2.  Thanks!
