### ISSUE TITLE
Pass local helpers to sub templates.

### ISSUE THREAD

**Issue by honzatrtik** [bitovi/canjs#734]
I need to add rendered element to context (can.Map instance). I am able to accomplish this using `{{(el) -> scope._context.attr('element', el)}}` but it seems to be ugly...

**Comment by cklanac** [comment]
Fixed in previous release. If you check the original fiddle http://jsfiddle.net/VVQ8k/1/ and open console, you'll see that the child nodes have an element attribute set to "li" element
