### ISSUE TITLE
API for controlling the behavior of Model.store.

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#738]
Some times there is a need to be able manually manage Model.store.

Currently model instance is removed from store when all the event binding removed from DOM and data layer.

Here is the case:

1) Some model that I loaded and present using some component, let say the component is the content of the tabs widget.
2) Then user switches off the tab and the component is removed. All the bindings are moved from DOM. And model is removed from store. But there are references to the model instance and actually it is meant be kept it memory for further actions - when the tab is switched back, component initiated again and renders the instance.
3) Then during due to some actions model data is updated from from server and if instance is removed from store there is incorrect behaviour,

So we can add:

Model.storeAll() - to make persistent storage
Model.storeRemove(id) - remove instance from store manually

**Comment by justinbmeyer** [comment]
Closing.  Binding handlers is the way to go.  We could make it more simple.  `model.bind()`, `model.unbind()`.  If you like that, please create another issue.
