### ISSUE TITLE
Passing whole scope to component

### ISSUE THREAD

**Issue by whitecolor** [bitovi/canjs#745]
The case, say  I have a model:

```javascript
track: {
   title: ...
   mediaFile: {filename: ..., url: ..., size: ....}
}
```
I have ```<my-track>``` component to work with track model and I want to create a separate component to work with mediaFile object ```<media-file>```.

If I want to pass a whole object to the component I have to do:
```javascript
<my-track>
    <media-file media-file="mediaFile"></media-file> 
</my-track>
```
but if the component assumes working only with mediaFile attributes there is not sense to have mediaFile in ```<media-file>``` scope, the scope could just have all the properties of mediaFile (filename, url, size)

```javascript
{{#mediaFile}}
    <media-file url="url" filename="filename" size="size"></media-file>
{{/mediaFile}}
```
but the last looks cumbersome.

Maybe consider something way to put a whole object in component's scope
```javascript
{{#mediaFile}}<media-file scope="this"></media-file>{{/mediaFile}}
```

**Comment by alexisabril** [comment]
@whitecolor You could use a subtemplate instead of a new component:

```
<my-track>
  <!-- this would keep the context, but let you separate your markup -->
  {{>media-file}}
</my-track>
```

As an alternative, you could set the view model directly by using viewModel's function syntax:

```
var Child = can.Component.extend({
  tag: 'sample-child',
  template: can.stache('{{foo}}'),
  viewModel: function(attrs, parentVM) {
    return parentVM;
  }
});
```

Example: http://jsbin.com/kayeza/edit?js,console,output
