### ISSUE TITLE
Maximum call stack size exceeded when calling can.Map.List.replace with big array

### ISSUE THREAD

**Issue by janza** [bitovi/canjs#779]
Try the following in chrome:

    var a = [], l = new can.Map.List([]);
    for(var i=0; i<50000; i++){
        a.push(1);
    }
    l.replace(a);

**Comment by alexisabril** [comment]
This is a limit on using splice.apply with an object(instance of can.List) as the context. Example breaking in Chrome 43.0.2357.132(Mac) without CanJS: http://jsbin.com/siqene/edit?js,console

With a simple array, there's a much higher threshold, so there may be a performance gain to be made here.

**Comment by daffl** [comment]
Closing since I don't think there is much we can do.
