### ISSUE TITLE
can.Map.setter merged properties example does not execute

### ISSUE THREAD

**Issue by shcarrico** [bitovi/canjs#806]
we need to add an init for the 'info' property ala the below to make the example code run

http://canjs.com/docs/can.Map.setter.html#section_DifferencesFromattr

```javascript
var Contact = can.Map.extend({
        info : new can.Map(), // this is new
        setInfo: function (raw) {
            this.info.attr(raw);
            return this.info;
        }
    });
```
fiddle here http://jsfiddle.net/shcarrico/DBBGD/

i suggest we update doc accordingly, and explain why (because example is merging a map, map has to exist so you can call attr on it right away)

**Comment by alexisabril** [comment]
Closing as setters are deprecated in favor of the define plugin: http://canjs.com/docs/can.Map.prototype.define.set.html
