### ISSUE TITLE
Replacing can.Map.List and can.List.Map

### ISSUE THREAD

**Issue by moschel** [bitovi/canjs#897]
Hopefully before 2.1, we should add wildcards to can/map/define that replace the same functionality of can.Map.List and can.List.Map.

On a List, the * would catch anything that doesn't have another definition:
```js
"*" : {type: MyMap }
```

Same on a Map:
```js
"*" {type: MyList}
```

And this would allow us to deprecate can.Map.List and can.List.Map

**Comment by daffl** [comment]
Closed via #1425
